/* /sitemap.xml — every page that exists, built when it is asked for.
 *
 * WHY A FUNCTION AND NOT A FILE. The static sitemap.xml carried thirteen URLs
 * and not one of them was a board, months after the board permalinks shipped:
 * hundreds of pages with no route in from search. A hand-kept file was never
 * going to hold them, because a new board appears EVERY DAY and the file only
 * changes when somebody deploys. A build step would be stale by the next
 * morning. So this is derived at request time from the same rules the pages
 * themselves keep.
 *
 * WHAT IS IN IT, and nothing else:
 *   the static pages          the hub, each game, the answers, archive and
 *                             club indexes
 *   every board that exists   /<game>/daily/<key>, for the five live games
 *
 * WHAT IS NOT, and why each absence is deliberate:
 *   tomorrow's board          the future is shut; naming it leaks the schedule
 *   a day a game did not run  those 404 now, and a sitemap listing a 404 is
 *                             worse than one listing nothing
 *   unreleased games          an unbuilt game is named nowhere served
 *
 * ONE RULE, ASKED NOT RESTATED. Which boards are public is permalink.js's
 * answer — todayKeyFor for the count, the schedule for whether a game ran that
 * day — and this calls it rather than keeping a second copy that would drift
 * the first time either changed.
 */
import { PERMA_GAMES, boardKeys, permalinkPath, gamePath } from "./_lib/permalink.js";

const SITE = "https://www.thexigames.com";

/* The pages that are not boards. Ordered as a reader would meet them, and
   listed rather than derived because that is what they are: a fixed set. */
const STATIC = [
  ["/", "daily", "1.0"],
  ["/football/crossword/", "daily", "0.9"],
  ["/football/wordsearch/", "daily", "0.9"],
  ["/football/scrambled/", "daily", "0.9"],
  ["/football/vowels/", "daily", "0.9"],
  ["/football/hilo/", "daily", "0.9"],
  ["/football/grid/", "daily", "0.9"],
  ["/football/crossword/answers/", "daily", "0.7"],
  ["/football/wordsearch/answers/", "daily", "0.7"],
  /* Three games had no answers archive until 6 Sep 2026 — the crossword got
     one, the word search copied it, and the three built afterwards were never
     given theirs. The index is what a crawler finds the individual boards
     from, so it is listed and they are not. */
  ["/football/scrambled/answers/", "daily", "0.7"],
  ["/football/vowels/answers/", "daily", "0.7"],
  ["/football/hilo/answers/", "daily", "0.7"],
  ["/football/grid/answers/", "daily", "0.7"],
  ["/football/crossword/clubs/", "weekly", "0.6"],
  ["/football/wordsearch/themes/", "weekly", "0.6"],
  ["/football/hilo/clubs/", "weekly", "0.6"],
  ["/football/crossword/how-to-play", "monthly", "0.5"],
  ["/football/crossword/privacy", "yearly", "0.3"],
];

/* AND EVERY GAME'S ARCHIVE INDEX, derived rather than listed. The five rows
   above for the answers indexes are hand-kept and that is defensible for a
   fixed set — but a page that exists for every game in PERMA_GAMES should be
   asked for, not remembered: the list above already went a whole game out of
   date once, and the sitemap was the file that had to be fixed. Daily,
   because a board joins each of these every morning. */
const ARCHIVES = Object.keys(PERMA_GAMES).map((g) => [gamePath(g) + "archive/", "daily", "0.7"]);

/* A board's own address for every game, in one place — and that place is
   permalink.js, which is also where the route decides whether it will serve
   one. This file kept its own copy of the rule and its own schedule query
   until the archive pages needed the same list; three copies of "which boards
   exist" is three answers the first time a game changes how it schedules. */
async function boardPaths(env) {
  const out = [];
  for (const game of Object.keys(PERMA_GAMES)) {
    for (const key of await boardKeys(env, game)) out.push(permalinkPath(game, key));
  }
  return out;
}

const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

export async function onRequestGet({ env }) {
  const rows = [
    ...[...STATIC, ...ARCHIVES].map(([path, freq, pri]) =>
      `  <url><loc>${esc(SITE + path)}</loc><changefreq>${freq}</changefreq><priority>${pri}</priority></url>`),
    /* A board never changes once it has run — that is the entire promise of a
       permalink — so a crawler is told not to come back for it. */
    ...(await boardPaths(env)).map((path) =>
      `  <url><loc>${esc(SITE + path)}</loc><changefreq>never</changefreq><priority>0.5</priority></url>`),
  ];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by functions/sitemap.xml.js. A new board appears every day, so
     this is derived when it is asked for rather than kept by hand: the file it
     replaced listed thirteen URLs and no boards at all. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${rows.join("\n")}
</urlset>
`;

  return new Response(xml, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      /* Cached at the edge for an hour. A board joins the sitemap the day it
         runs and never changes after, so an hour behind is nothing — and it
         keeps a crawler from rebuilding this on every hit. */
      "Cache-Control": "public, max-age=0, s-maxage=3600",
    },
  });
}
