/* config.js — every tunable in Who Am I XI lives here and nowhere else.
   Change a number, reload the page, play again. No build step needed.

   THE CLUE LADDER IS CONFIGURATION, NOT STRUCTURE, and that is deliberate: the
   owner is play-testing what a substitution should buy, and a ladder baked into
   the endpoints would make every answer to that question a code change. The
   SERVER reads this file rather than keeping its own copy — the same way
   QuickFire's scoring bands are read by both sides — because a ladder the page
   drew from one table and the server charged from another would disagree the
   first time anybody tuned one.
*/
(function (root) {
  'use strict';

  var CONFIG = {
    /* --- The board ---------------------------------------------------- */
    DOORS_PER_BOARD: 11,           // core rule — an XI of clubs

    /* --- The match clock ------------------------------------------------
       Ninety minutes, and the score falls from 114 along the family's curve —
       the same frame as HiLo, Ballpark, the crossword and Codeword, so a 90
       here means what a 90 means anywhere else and the season can add them up.
       The curve itself is NOT here: it is functions/_lib/xi-score.js, read by
       both sides, because a page curve and a server curve would agree the day
       they were written and disagree the first time anybody tuned one. */
    MATCH_MINUTES: 90,
    /* Real seconds to the match minute. Twenty is a thirty-minute match, which
       is the pace a game you think about wants; Codeword offers three as well
       for anyone who would rather sprint. */
    RATE_SECONDS: 20,

    /* --- The clue ladder ------------------------------------------------
       Stage 1 is free and is what you get for opening a door. Each stage after
       it COSTS POINTS, deducted from whatever the clock has left you.
       `reveals` names what the server is allowed to send at that stage and
       nothing else may leave on its account — functions/_lib/wa-play.js reads
       these names.

       POINTS RATHER THAN MINUTES, which is where this differs from Codeword.
       Codeword charges its helpers in match minutes and lets the curve turn
       them into points, which works because its helpers are small and
       repeatable. Here there are three, they are large, and each one changes
       what the puzzle IS — the career is most of the answer. A flat price says
       so plainly: you can see what a clue costs before you buy it, rather than
       working out what ten minutes is worth at the minute you happen to be at.

       WHY THE CAREER IS STAGE 2 AND NOT STAGE 1. It IS the answer:
       "Cobreloa, Udinese, Barcelona, Arsenal, Man United, Inter" is Sanchez to
       anyone who can read it. Stage 1 is one spell — the door's own club, its
       years and its appearances — which narrows without naming. And it is the
       dearest rung for the same reason.

       GIVING UP COSTS EVERYTHING, which is not a penalty but an accounting:
       a board you were told the answer to scored nothing, and pricing it at
       anything less would make the reveal a cheap way to a number. */
    LADDER: [
      /* GENERATED by tools/build_friendswhoami.js. A round deals three clues,
         hard to easy; the first is free and the next two cost. */
      { stage: 1, points: 0, sub: 0, label: 'First clue',  reveals: ['clue'] },
      { stage: 2, points: 4, sub: 1, label: 'Second clue', reveals: ['clue'] },
      { stage: 3, points: 3, sub: 2, label: 'Third clue',  reveals: ['clue'] }
    ],

    /* TWO SUBSTITUTIONS, NOT THREE. There was a third and it was "give up",
       which is not a substitution — it is leaving the pitch. A bench of three
       was the family's shape borrowed without asking what the third would BUY,
       and the honest answer was nothing: the spell, the career and the bio are
       everything this game knows about a player that is not his name.
       Giving up is kept as an action because a board you cannot finish has to
       end somehow, but it is not a rung and it is not priced. It ends the board
       at nothing, which is not a penalty but an accounting: a board you were
       told the answer to scored nothing. */
    GIVE_UP: { label: 'Give up', reveals: ['answer'] },

    /* Both substitutions bought, derived from the ladder rather than stated
       twice — change a price and this follows. */
    get CLUES_TOTAL_COST() {
      return this.LADDER.reduce(function (a, s) { return a + s.points; }, 0);
    },
    get SUBS_PER_BOARD() {
      return this.LADDER.filter(function (s) { return s.points > 0; }).length;
    },

    /* --- Guessing ------------------------------------------------------- */
    /* NAMING SOMEBODY WHO DID PLAY FOR THAT CLUB is its own outcome and costs
       nothing. It is a near miss rather than a mistake, and charging for it
       would punish the one kind of wrong answer that means the player has
       understood the door. Decided server-side: the alternative is handing the
       page the club's full roster, which is a candidate list. */
    WRONG_PLAYER_SAME_CLUB_COSTS_SUB: false,
    /* A plain wrong name costs nothing either — the substitutions are spent on
       CLUES, and the tension is how many you need rather than how many you
       waste. Set to true to test the other shape. */
    WRONG_GUESS_COSTS_SUB: false,

    /* --- The type-ahead -------------------------------------------------- */
    MIN_CHARS_TO_SEARCH: 2,        // below this, show nothing rather than 3,146
    MAX_SUGGESTIONS: 8,

    /* --- Storage --------------------------------------------------------- */
    // The namespace is PREFIX in game.js, which is where aligned_test reads it
    // from. This is the rest of the key, not a second copy of the prefix.
    STORAGE_KEY: 'daily.v1'
  };

  if (typeof module !== 'undefined' && module.exports) module.exports = CONFIG;
  root.XIWA_CONFIG = CONFIG;
})(typeof globalThis !== 'undefined' ? globalThis : this);
