-- 047-friends-lightning.sql — Lightning Round (Friends): the pool, the daily
-- run, the sittings and what each player has recently seen.
--
-- Lightning Round is sixty seconds of four-option questions: +1 a right answer,
-- three seconds off the clock for a wrong one. The clock, the marking and the
-- score are this server's, for QuickFire's reason: a page that holds the answer
-- or the clock is a page that chooses its own score.
--
-- THE POOL IS LOADED FROM OUTSIDE THE REPO. fr-lightning-production.sql is
-- generated by LightningRoundXI_Friends/scripts/build_pool.py from the
-- QuickFire Friends option bank, and banks are never committed here.
--
-- Applied once. Every statement is CREATE ... IF NOT EXISTS, so re-running it
-- is safe.

-- The questions. Replaced wholesale by the pool file; a run keeps the ids it
-- was dealt, so a question dropped from the pool simply stops being drawn.
CREATE TABLE IF NOT EXISTS fr_lr_question (
  id        TEXT PRIMARY KEY,          -- the bank's id, e.g. EVT0590
  diff      TEXT NOT NULL,             -- Easy | Medium | Hard
  clue      TEXT NOT NULL,
  answer    TEXT NOT NULL,             -- never leaves the server unsettled
  option_1  TEXT NOT NULL,
  option_2  TEXT NOT NULL,
  option_3  TEXT NOT NULL,
  option_4  TEXT NOT NULL,
  pgk       TEXT                       -- the subject, so a run does not ask about Ross five times running
);

-- Two questions that must never share a run: one names the other's answer
-- (FRQF-leak-pairs.csv), or both ask the same thing (duplicate groups).
-- Stored once, a < b.
CREATE TABLE IF NOT EXISTS fr_lr_pair (
  a TEXT NOT NULL,
  b TEXT NOT NULL,
  PRIMARY KEY (a, b)
);

-- The day's run, dealt once and kept. Dealt from the date as a seed, and then
-- STORED, so a pool rebuilt at noon does not hand the afternoon a different
-- daily from the morning's.
CREATE TABLE IF NOT EXISTS fr_lr_daily (
  play_date TEXT PRIMARY KEY,          -- YYYY-MM-DD, the server's UTC day
  seq       TEXT NOT NULL              -- JSON array of question ids, in order
);

-- A sitting. The clock starts when the row is written and is never sent up.
CREATE TABLE IF NOT EXISTS fr_lr_run (
  run_id      TEXT PRIMARY KEY,
  mode        TEXT NOT NULL,           -- daily | practice
  play_date   TEXT NOT NULL,           -- the server's UTC day at the start
  user_id     TEXT,                    -- signed in, or NULL
  seed        TEXT NOT NULL,           -- what dealt the options' order
  seq         TEXT NOT NULL,           -- JSON array of question ids, in order
  started_ms  INTEGER NOT NULL,
  penalty_ms  INTEGER NOT NULL DEFAULT 0,   -- wrong answers, charged to the clock
  served      INTEGER NOT NULL DEFAULT 1,   -- the question now on screen, 1-based
  score       INTEGER NOT NULL DEFAULT 0,
  wrong       INTEGER NOT NULL DEFAULT 0,
  finished_ms INTEGER                  -- set once, by /finish
);
CREATE INDEX IF NOT EXISTS fr_lr_run_user ON fr_lr_run (user_id, play_date, mode);

-- One locked pick per question per run. The primary key is the anti-replay
-- rule: a retried request cannot answer the same question twice and keep the
-- better outcome.
CREATE TABLE IF NOT EXISTS fr_lr_answer (
  run_id      TEXT NOT NULL,
  idx         INTEGER NOT NULL,
  question_id TEXT NOT NULL,
  pick        TEXT NOT NULL,
  correct     INTEGER NOT NULL,
  at_ms       INTEGER NOT NULL,
  PRIMARY KEY (run_id, idx)
);

-- What a signed-in player has been served, so practice can avoid it. A
-- signed-out player's list lives in their browser and is sent up with /start.
CREATE TABLE IF NOT EXISTS fr_lr_seen (
  user_id     TEXT NOT NULL,
  question_id TEXT NOT NULL,
  seen_ms     INTEGER NOT NULL,
  PRIMARY KEY (user_id, question_id)
);
CREATE INDEX IF NOT EXISTS fr_lr_seen_recent ON fr_lr_seen (user_id, seen_ms);
