/* GENERATED by tools/build_friendsscrambled.js — do not edit by hand.
 * Scrambled XI: Friends and Vowels XI: Friends: the prices. No clock. */
(function (root) {
  'use strict';
  var CONFIG = {
    /* No clock: nothing is timed, and nothing reads these as a clock. */
    MATCH_CLOCK_REAL_SECONDS: null,
    ANAGRAM_CLOCK_REAL_SECONDS: null,
    CONSONANT_CLOCK_REAL_SECONDS: null,
    REVEAL_LETTER_COST: 2,
    REVEAL_VOWEL_COST: 2,
    /* Giving an answer up costs what it was worth. */
    REVEAL_NAME_COST: 20,
    /* No board in this set sells a hint; priced so a stray call costs a hint. */
    REVEAL_HINT_COST: 3,
    HALF_TIME_MINUTE: null,
    SECOND_HALF_LETTERS: false,
    PAUSE_ON_TAB_HIDDEN: true,
    STORAGE_KEY: 'board.v1'
  };
  if (typeof module !== 'undefined' && module.exports) module.exports = CONFIG;
  root.SCX_FR_CONFIG = CONFIG;
})(typeof globalThis !== 'undefined' ? globalThis : this);
