/* GENERATED by tools/build_friendsscrambled.js — do not edit by hand.
 * Scrambled XI: Friends and Vowels XI: Friends: the score. No clock. */
(function (root) {
  'use strict';
  var PER_ANSWER = 20;
  var MAX_SCORE = PER_ANSWER * 5;
  function matchMinute() { return 0; }
  function timePenalty() { return 0; }
  function computeScore(elapsedSeconds, help) {
    var hp = Math.max(0, help || 0);
    return { score: Math.max(0, MAX_SCORE - hp), timePenalty: 0, helpPenalty: hp };
  }
  var api = {
    PER_ANSWER: PER_ANSWER,
    MAX_SCORE: MAX_SCORE,
    matchMinute: matchMinute,
    timePenalty: timePenalty,
    computeScore: computeScore
  };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  root.SCX_FR_SCORING = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
