/* bp-sample.js — two Ballpark XI boards, so the game runs with no database.
 *
 * GENERATED by tools/import_ballpark.js. Hand-editing it would make it a third
 * statement of what a board is, after the content side's bank and the D1 rows.
 */
export const BP_SAMPLE_BOARDS = [
 {
  "id": "bp-0001",
  "day": 1,
  "questions": [
   {
    "id": "arsenal-games-allison",
    "question": "How many games did George Allison manage Arsenal for?",
    "detail": "Every competition, his whole time in charge, from the club's own list of its managers.",
    "answer": 279,
    "lo": 184,
    "hi": 491,
    "tolerance": 17,
    "step": 1,
    "unit": "games",
    "kind": "manager-career",
    "family": "careers"
   },
   {
    "id": "appointed-alan-pardew-newcastle-united",
    "question": "In which year was Alan Pardew first appointed manager of Newcastle United?",
    "detail": "His first permanent spell at the club. Caretakers are not counted.",
    "answer": 2010,
    "lo": 2007,
    "hi": 2024,
    "tolerance": 1,
    "step": 1,
    "unit": "",
    "kind": "event-year",
    "family": "years"
   },
   {
    "id": "arsenal-games-chapman",
    "question": "How many games did Herbert Chapman manage Arsenal for?",
    "detail": "Every competition, his whole time in charge, from the club's own list of its managers.",
    "answer": 403,
    "lo": 110,
    "hi": 447,
    "tolerance": 24,
    "step": 1,
    "unit": "games",
    "kind": "manager-career",
    "family": "careers"
   },
   {
    "id": "appointed-alex-ferguson-manchester-united",
    "question": "In which year did Alex Ferguson take charge of Manchester United?",
    "detail": "His first permanent spell at the club, the year he was appointed.",
    "answer": 1986,
    "lo": 1984,
    "hi": 1997,
    "tolerance": 1,
    "step": 1,
    "unit": "",
    "kind": "event-year",
    "family": "years"
   },
   {
    "id": "city-pep-cl-milestone",
    "question": "How many matches did it take Pep Guardiola to reach 100 Champions League wins?",
    "detail": "The quickest anyone has done it, beating Carlo Ancelotti by 20 matches, as at the end of the 2025/26 season.",
    "answer": 160,
    "lo": 110,
    "hi": 183,
    "tolerance": 6,
    "step": 1,
    "unit": "matches",
    "kind": "games-to-milestone",
    "family": "careers"
   },
   {
    "id": "burnley-points",
    "question": "How many points did Burnley take winning the Championship in 2022/23?",
    "detail": "Under Vincent Kompany, in a 46-game season with three points for a win. The first Championship side to reach a century of points in nine years.",
    "answer": 101,
    "lo": 94,
    "hi": 131,
    "tolerance": 2,
    "step": 1,
    "unit": "points",
    "kind": "season-points",
    "family": "seasons"
   },
   {
    "id": "facup-drought-chelsea",
    "question": "How many years has it been since Chelsea last won the FA Cup?",
    "detail": "As at the end of the 2025/26 season. They last won it in 2018, one of 8, from 17 finals.",
    "answer": 8,
    "lo": 0,
    "hi": 36,
    "tolerance": 2,
    "step": 1,
    "unit": "years",
    "kind": "trophy-drought",
    "family": "years"
   },
   {
    "id": "england-caps-alan-shearer",
    "question": "How many England caps did Alan Shearer win?",
    "detail": "The men's senior team, full caps only. His career total.",
    "answer": 63,
    "lo": 56,
    "hi": 105,
    "tolerance": 4,
    "step": 1,
    "unit": "caps",
    "kind": "england-caps",
    "family": "careers"
   },
   {
    "id": "barcelona-spotify-deal",
    "question": "What is Barcelona's Spotify deal reported to be worth, in millions of euros?",
    "detail": "The 2022 agreement covering the stadium name and the shirt, in euros because both parties are European and the figure was reported in them.",
    "answer": 280,
    "lo": 264,
    "hi": 517,
    "tolerance": 14,
    "step": 1,
    "unit": "million euros",
    "kind": "money-millions",
    "family": "money"
   },
   {
    "id": "city-away-wins-2021",
    "question": "How many away league games did Manchester City win in the 2021 calendar year?",
    "detail": "An English top-flight record for a calendar year, set under Pep Guardiola.",
    "answer": 19,
    "lo": 10,
    "hi": 35,
    "tolerance": 2,
    "step": 1,
    "unit": "wins",
    "kind": "manager-season-wins",
    "family": "seasons"
   },
   {
    "id": "age-bennett-derby",
    "question": "How old was the youngest player ever to appear for Derby County?",
    "detail": "Mason Bennett, against Middlesbrough on 22 October 2011.",
    "answer": 15,
    "lo": 4,
    "hi": 17,
    "tolerance": 1,
    "step": 1,
    "unit": "years",
    "kind": "age-years",
    "family": "records",
    "strict": true
   }
  ]
 },
 {
  "id": "bp-0002",
  "day": 2,
  "questions": [
   {
    "id": "arsenal-games-graham",
    "question": "How many games did George Graham manage Arsenal for?",
    "detail": "Every competition, his whole time in charge, from the club's own list of its managers.",
    "answer": 460,
    "lo": 374,
    "hi": 879,
    "tolerance": 28,
    "step": 1,
    "unit": "games",
    "kind": "manager-career",
    "family": "careers"
   },
   {
    "id": "appointed-alex-mcleish-rangers",
    "question": "In which year did Alex McLeish take charge of Rangers?",
    "detail": "His first permanent spell at the club, the year he was appointed.",
    "answer": 2001,
    "lo": 1998,
    "hi": 2017,
    "tolerance": 1,
    "step": 1,
    "unit": "",
    "kind": "event-year",
    "family": "years"
   },
   {
    "id": "arsenal-games-howe",
    "question": "How many games did Don Howe manage Arsenal for?",
    "detail": "Every competition, his whole time in charge, from the club's own list of its managers.",
    "answer": 117,
    "lo": 17,
    "hi": 144,
    "tolerance": 7,
    "step": 1,
    "unit": "games",
    "kind": "manager-career",
    "family": "careers"
   },
   {
    "id": "appointed-alfredo-di-stefano-real-madrid",
    "question": "In which year was Alfredo Di Stefano first appointed manager of Real Madrid?",
    "detail": "His first permanent spell at the club. Caretakers are not counted.",
    "answer": 1982,
    "lo": 1971,
    "hi": 1990,
    "tolerance": 1,
    "step": 1,
    "unit": "",
    "kind": "event-year",
    "family": "years"
   },
   {
    "id": "england-caps-ashley-cole",
    "question": "How many England caps did Ashley Cole win?",
    "detail": "The men's senior team, full caps only. His career total.",
    "answer": 107,
    "lo": 91,
    "hi": 164,
    "tolerance": 6,
    "step": 1,
    "unit": "caps",
    "kind": "england-caps",
    "family": "careers"
   },
   {
    "id": "city-wins-2021",
    "question": "How many Premier League games did Manchester City win in the 2021 calendar year?",
    "detail": "An English top-flight record for a calendar year, set under Pep Guardiola.",
    "answer": 36,
    "lo": 34,
    "hi": 63,
    "tolerance": 2,
    "step": 1,
    "unit": "wins",
    "kind": "manager-season-wins",
    "family": "seasons"
   },
   {
    "id": "city-pep-league-cups",
    "question": "How many League Cups did Pep Guardiola win as a manager?",
    "detail": "A record for the competition, as at the end of the 2025/26 season. Alex Ferguson, Brian Clough and Jose Mourinho are next.",
    "answer": 5,
    "lo": 0,
    "hi": 24,
    "tolerance": 1,
    "step": 1,
    "unit": "League Cups",
    "kind": "honours-count",
    "family": "honours"
   },
   {
    "id": "facup-drought-liverpool",
    "question": "How many years has it been since Liverpool last won the FA Cup?",
    "detail": "As at the end of the 2025/26 season. They last won it in 2022, one of 8, from 15 finals.",
    "answer": 4,
    "lo": 0,
    "hi": 25,
    "tolerance": 2,
    "step": 1,
    "unit": "years",
    "kind": "trophy-drought",
    "family": "years"
   },
   {
    "id": "pl-alltime-goalsFor-blackburn-rovers",
    "question": "How many Premier League goals have Blackburn Rovers scored?",
    "detail": "Every Premier League season from 1992/93, up to and including 2025/26, across 18 seasons and 696 matches.",
    "answer": 927,
    "lo": 530,
    "hi": 1203,
    "tolerance": 56,
    "step": 1,
    "unit": "goals",
    "kind": "club-domestic",
    "family": "clubs"
   },
   {
    "id": "law-ball-circ-max",
    "question": "What is the largest circumference the ball may have, in centimetres?",
    "detail": "The upper end of the range the Laws allow.",
    "answer": 70,
    "lo": 62,
    "hi": 80,
    "tolerance": 1,
    "step": 1,
    "unit": "centimetres",
    "kind": "law-measure",
    "family": "laws"
   },
   {
    "id": "england-caps-bryan-robson",
    "question": "How many England caps did Bryan Robson win?",
    "detail": "The men's senior team, full caps only. His career total.",
    "answer": 90,
    "lo": 80,
    "hi": 151,
    "tolerance": 5,
    "step": 1,
    "unit": "caps",
    "kind": "england-caps",
    "family": "careers"
   }
  ]
 }
];

/* The calendar, as OFFSETS from today rather than as dates: a fixture with a
   date written into it stops being today, and then reports a fault in the code
   when the fault is in the fixture. */
export const BP_SAMPLE_SCHEDULE = {"0":"bp-0002","-1":"bp-0001"};
