/* gd-sample.js — two Grid XI boards, so the game runs with no database.
 *
 * The same arrangement HiLo and the word search keep: the BANK is 256 boards
 * and lives outside the repository, and this is a sample small enough to commit
 * and complete enough for a suite to play. Every offline run — every check in
 * CI, and `wrangler pages dev` on a machine with no D1 — sees these two and
 * says so, rather than a game that will not open.
 *
 * YES, THE ANSWERS ARE IN HERE, and that is the same trade the other two make.
 * A sample carrying no answers could not be played and so could not be tested,
 * and two boards out of 256 is not the bank. What must never happen is a
 * board reaching a BROWSER with its letters, which is a different question and
 * is what gd-board.js publicBoard and football/grid/api_test.mjs are for.
 *
 * GENERATED by tools/import_grid.js. Hand-editing it would make it a third
 * statement of what a board is, after the emitter and the D1 rows.
 */
export const GD_SAMPLE_BOARDS = [
 {
  "id": "gx-0082",
  "set_id": "fifpro-world-11-2008",
  "kind": "daily",
  "title": "FIFPro World XI — 2008",
  "rows": 9,
  "cols": 13,
  "entries": [
   {
    "n": 1,
    "dir": "across",
    "r": 4,
    "c": 0,
    "len": 9,
    "cells": [
     "4,0",
     "4,1",
     "4,2",
     "4,3",
     "4,4",
     "4,5",
     "4,6",
     "4,7",
     "4,8"
    ],
    "answer": "FERDINAND",
    "member": "Rio Ferdinand"
   },
   {
    "n": 2,
    "dir": "down",
    "r": 2,
    "c": 2,
    "len": 5,
    "cells": [
     "2,2",
     "3,2",
     "4,2",
     "5,2",
     "6,2"
    ],
    "answer": "TERRY",
    "member": "John Terry"
   },
   {
    "n": 3,
    "dir": "down",
    "r": 0,
    "c": 6,
    "len": 7,
    "cells": [
     "0,6",
     "1,6",
     "2,6",
     "3,6",
     "4,6",
     "5,6",
     "6,6"
    ],
    "answer": "GERRARD",
    "member": "Steven Gerrard"
   },
   {
    "n": 4,
    "dir": "across",
    "r": 2,
    "c": 6,
    "len": 7,
    "cells": [
     "2,6",
     "2,7",
     "2,8",
     "2,9",
     "2,10",
     "2,11",
     "2,12"
    ],
    "answer": "RONALDO",
    "member": "Cristiano Ronaldo"
   },
   {
    "n": 5,
    "dir": "down",
    "r": 1,
    "c": 4,
    "len": 8,
    "cells": [
     "1,4",
     "2,4",
     "3,4",
     "4,4",
     "5,4",
     "6,4",
     "7,4",
     "8,4"
    ],
    "answer": "CASILLAS",
    "member": "Iker Casillas"
   },
   {
    "n": 6,
    "dir": "down",
    "r": 1,
    "c": 12,
    "len": 6,
    "cells": [
     "1,12",
     "2,12",
     "3,12",
     "4,12",
     "5,12",
     "6,12"
    ],
    "answer": "TORRES",
    "member": "Fernando Torres"
   },
   {
    "n": 7,
    "dir": "across",
    "r": 6,
    "c": 8,
    "len": 5,
    "cells": [
     "6,8",
     "6,9",
     "6,10",
     "6,11",
     "6,12"
    ],
    "answer": "RAMOS",
    "member": "Sergio Ramos"
   },
   {
    "n": 8,
    "dir": "down",
    "r": 5,
    "c": 9,
    "len": 4,
    "cells": [
     "5,9",
     "6,9",
     "7,9",
     "8,9"
    ],
    "answer": "KAKA",
    "member": "Kaká"
   },
   {
    "n": 9,
    "dir": "across",
    "r": 8,
    "c": 1,
    "len": 5,
    "cells": [
     "8,1",
     "8,2",
     "8,3",
     "8,4",
     "8,5"
    ],
    "answer": "MESSI",
    "member": "Lionel Messi"
   },
   {
    "n": 10,
    "dir": "across",
    "r": 6,
    "c": 0,
    "len": 5,
    "cells": [
     "6,0",
     "6,1",
     "6,2",
     "6,3",
     "6,4"
    ],
    "answer": "PUYOL",
    "member": "Carles Puyol"
   },
   {
    "n": 11,
    "dir": "across",
    "r": 8,
    "c": 8,
    "len": 4,
    "cells": [
     "8,8",
     "8,9",
     "8,10",
     "8,11"
    ],
    "answer": "XAVI",
    "member": "Xavi"
   }
  ],
  "crossings": [
   {
    "cell": "4,2",
    "entries": [
     1,
     2
    ],
    "at": [
     2,
     2
    ]
   },
   {
    "cell": "4,4",
    "entries": [
     1,
     5
    ],
    "at": [
     4,
     3
    ]
   },
   {
    "cell": "4,6",
    "entries": [
     1,
     3
    ],
    "at": [
     6,
     4
    ]
   },
   {
    "cell": "6,2",
    "entries": [
     2,
     10
    ],
    "at": [
     4,
     2
    ]
   },
   {
    "cell": "2,6",
    "entries": [
     3,
     4
    ],
    "at": [
     2,
     0
    ]
   },
   {
    "cell": "2,12",
    "entries": [
     4,
     6
    ],
    "at": [
     6,
     1
    ]
   },
   {
    "cell": "6,4",
    "entries": [
     5,
     10
    ],
    "at": [
     5,
     4
    ]
   },
   {
    "cell": "8,4",
    "entries": [
     5,
     9
    ],
    "at": [
     7,
     3
    ]
   },
   {
    "cell": "6,12",
    "entries": [
     6,
     7
    ],
    "at": [
     5,
     4
    ]
   },
   {
    "cell": "6,9",
    "entries": [
     7,
     8
    ],
    "at": [
     1,
     1
    ]
   },
   {
    "cell": "8,9",
    "entries": [
     8,
     11
    ],
    "at": [
     3,
     1
    ]
   }
  ],
  "quality": {
   "crossings": 11,
   "mean": 2,
   "min": 1
  }
 },
 {
  "id": "gx-0256",
  "set_id": "premier-league-grounds-over-30000-2026-27",
  "kind": "daily",
  "title": "Premier League grounds with a capacity above 30,000 (2026–27)",
  "rows": 16,
  "cols": 16,
  "entries": [
   {
    "n": 1,
    "dir": "across",
    "r": 8,
    "c": 0,
    "len": 16,
    "cells": [
     "8,0",
     "8,1",
     "8,2",
     "8,3",
     "8,4",
     "8,5",
     "8,6",
     "8,7",
     "8,8",
     "8,9",
     "8,10",
     "8,11",
     "8,12",
     "8,13",
     "8,14",
     "8,15"
    ],
    "answer": "TOTTENHAMHOTSPUR",
    "member": "Tottenham Hotspur Stadium"
   },
   {
    "n": 2,
    "dir": "down",
    "r": 2,
    "c": 12,
    "len": 11,
    "cells": [
     "2,12",
     "3,12",
     "4,12",
     "5,12",
     "6,12",
     "7,12",
     "8,12",
     "9,12",
     "10,12",
     "11,12",
     "12,12"
    ],
    "answer": "STJAMESPARK",
    "member": "St James' Park"
   },
   {
    "n": 3,
    "dir": "down",
    "r": 1,
    "c": 0,
    "len": 13,
    "cells": [
     "1,0",
     "2,0",
     "3,0",
     "4,0",
     "5,0",
     "6,0",
     "7,0",
     "8,0",
     "9,0",
     "10,0",
     "11,0",
     "12,0",
     "13,0"
    ],
    "answer": "ETIHADSTADIUM",
    "member": "City of Manchester Stadium"
   },
   {
    "n": 4,
    "dir": "down",
    "r": 1,
    "c": 14,
    "len": 10,
    "cells": [
     "1,14",
     "2,14",
     "3,14",
     "4,14",
     "5,14",
     "6,14",
     "7,14",
     "8,14",
     "9,14",
     "10,14"
    ],
    "answer": "CITYGROUND",
    "member": "Stamford Bridge"
   },
   {
    "n": 5,
    "dir": "down",
    "r": 4,
    "c": 5,
    "len": 10,
    "cells": [
     "4,5",
     "5,5",
     "6,5",
     "7,5",
     "8,5",
     "9,5",
     "10,5",
     "11,5",
     "12,5",
     "13,5"
    ],
    "answer": "ELLANDROAD",
    "member": "Elland Road"
   },
   {
    "n": 6,
    "dir": "down",
    "r": 0,
    "c": 10,
    "len": 11,
    "cells": [
     "0,10",
     "1,10",
     "2,10",
     "3,10",
     "4,10",
     "5,10",
     "6,10",
     "7,10",
     "8,10",
     "9,10",
     "10,10"
    ],
    "answer": "PORTMANROAD",
    "member": "Hill Dickinson Stadium"
   },
   {
    "n": 7,
    "dir": "across",
    "r": 5,
    "c": 0,
    "len": 7,
    "cells": [
     "5,0",
     "5,1",
     "5,2",
     "5,3",
     "5,4",
     "5,5",
     "5,6"
    ],
    "answer": "ANFIELD",
    "member": "Anfield"
   },
   {
    "n": 8,
    "dir": "across",
    "r": 0,
    "c": 5,
    "len": 9,
    "cells": [
     "0,5",
     "0,6",
     "0,7",
     "0,8",
     "0,9",
     "0,10",
     "0,11",
     "0,12",
     "0,13"
    ],
    "answer": "VILLAPARK",
    "member": "Villa Park"
   },
   {
    "n": 9,
    "dir": "down",
    "r": 3,
    "c": 3,
    "len": 8,
    "cells": [
     "3,3",
     "4,3",
     "5,3",
     "6,3",
     "7,3",
     "8,3",
     "9,3",
     "10,3"
    ],
    "answer": "EMIRATES",
    "member": "Emirates Stadium"
   },
   {
    "n": 10,
    "dir": "down",
    "r": 2,
    "c": 8,
    "len": 14,
    "cells": [
     "2,8",
     "3,8",
     "4,8",
     "5,8",
     "6,8",
     "7,8",
     "8,8",
     "9,8",
     "10,8",
     "11,8",
     "12,8",
     "13,8",
     "14,8",
     "15,8"
    ],
    "answer": "STADIUMOFLIGHT",
    "member": "Stadium of Light"
   },
   {
    "n": 11,
    "dir": "across",
    "r": 15,
    "c": 5,
    "len": 11,
    "cells": [
     "15,5",
     "15,6",
     "15,7",
     "15,8",
     "15,9",
     "15,10",
     "15,11",
     "15,12",
     "15,13",
     "15,14",
     "15,15"
    ],
    "answer": "OLDTRAFFORD",
    "member": "Old Trafford"
   }
  ],
  "crossings": [
   {
    "cell": "8,0",
    "entries": [
     1,
     3
    ],
    "at": [
     0,
     7
    ]
   },
   {
    "cell": "8,3",
    "entries": [
     1,
     9
    ],
    "at": [
     3,
     5
    ]
   },
   {
    "cell": "8,5",
    "entries": [
     1,
     5
    ],
    "at": [
     5,
     4
    ]
   },
   {
    "cell": "8,8",
    "entries": [
     1,
     10
    ],
    "at": [
     8,
     6
    ]
   },
   {
    "cell": "8,10",
    "entries": [
     1,
     6
    ],
    "at": [
     10,
     8
    ]
   },
   {
    "cell": "8,12",
    "entries": [
     1,
     2
    ],
    "at": [
     12,
     6
    ]
   },
   {
    "cell": "8,14",
    "entries": [
     1,
     4
    ],
    "at": [
     14,
     7
    ]
   },
   {
    "cell": "5,0",
    "entries": [
     3,
     7
    ],
    "at": [
     4,
     0
    ]
   },
   {
    "cell": "5,5",
    "entries": [
     5,
     7
    ],
    "at": [
     1,
     5
    ]
   },
   {
    "cell": "0,10",
    "entries": [
     6,
     8
    ],
    "at": [
     0,
     5
    ]
   },
   {
    "cell": "5,3",
    "entries": [
     7,
     9
    ],
    "at": [
     3,
     2
    ]
   },
   {
    "cell": "15,8",
    "entries": [
     10,
     11
    ],
    "at": [
     13,
     3
    ]
   }
  ],
  "quality": {
   "crossings": 12,
   "mean": 2.182,
   "min": 1
  }
 }
];

/* The calendar, as OFFSETS from today. -1 is yesterday, so the archive has one
   board and today has the other. */
export const GD_SAMPLE_SCHEDULE = {"0":"gx-0256","-1":"gx-0082"};
