/* hl-sample.js — GENERATED by tools/import_hilo.js. Do not edit.
 *
 * Three real boards and the two calendar days they stand on: what the Worker
 * falls back to with no database bound, and what the suites play. The bank
 * lives outside the repository; this is a sample of it, and small on purpose
 * so committing the bank by accident would show in a diff. */
export const HL_SAMPLE_BOARDS = [
 {
  "id": "1015",
  "category": "Premier League players by age",
  "subtitle": "Older or younger? The value is the year he was born, and the reveal shows his age today.",
  "unit": "year",
  "valueClass": "fixed-by-nature",
  "trueAsOf": "2026-09-02",
  "chain": [
   {
    "name": "Ross Barkley",
    "value": 1993,
    "context": "English midfielder, 307 Premier League appearances",
    "detail": {
     "nameRaw": "Ross Barkley",
     "born": "5 December 1993",
     "birthDate": "1993-12-05",
     "leaguePlayerId": "4115",
     "appearances": 307
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/appearances?comps=1&pageSize=100&page=1",
     "page": "the league feed, one hundred rows a page; this row is rank 148 on page 2",
     "quote": "\"label\":\"5 December 1993\"},\"country\":{\"isoCode\":\"GB-ENG\",\"country\":\"England\",\"demonym\":\"English\"},\"place\":\"Liverpool\"},\"age\":\"32 years 271 days\",\"name\":{\"display\":\"Ross Barkley\"",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Jamie Vardy",
    "value": 1987,
    "context": "English forward, 342 Premier League appearances",
    "detail": {
     "nameRaw": "Jamie Vardy",
     "born": "11 January 1987",
     "birthDate": "1987-01-11",
     "leaguePlayerId": "8979",
     "appearances": 342
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/appearances?comps=1&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 92 on page 1",
     "quote": "\"label\":\"11 January 1987\"},\"country\":{\"isoCode\":\"GB-ENG\",\"country\":\"England\",\"demonym\":\"English\"},\"place\":\"Sheffield\"},\"age\":\"39 years 234 days\",\"name\":{\"display\":\"Jamie Vardy\"",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Rio Ferdinand",
    "value": 1978,
    "context": "English defender, 504 Premier League appearances",
    "detail": {
     "nameRaw": "Rio Ferdinand",
     "born": "7 November 1978",
     "birthDate": "1978-11-07",
     "leaguePlayerId": "1111",
     "appearances": 504
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/appearances?comps=1&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 11 on page 1",
     "quote": "\"label\":\"7 November 1978\"},\"country\":{\"isoCode\":\"GB-ENG\",\"country\":\"England\",\"demonym\":\"English\"}},\"age\":\"47 years 299 days\",\"name\":{\"display\":\"Rio Ferdinand\"",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Stephen Carr",
    "value": 1976,
    "context": "Irish defender, 377 Premier League appearances",
    "detail": {
     "nameRaw": "Stephen Carr",
     "born": "29 August 1976",
     "birthDate": "1976-08-29",
     "leaguePlayerId": "776",
     "appearances": 377
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/appearances?comps=1&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 61 on page 1",
     "quote": "\"label\":\"29 August 1976\"},\"country\":{\"isoCode\":\"IE\",\"country\":\"Ireland\",\"demonym\":\"Irish\"}},\"age\":\"50 years 4 days\",\"name\":{\"display\":\"Stephen Carr\"",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Richard Dunne",
    "value": 1979,
    "context": "Irish defender, 431 Premier League appearances",
    "detail": {
     "nameRaw": "Richard Dunne",
     "born": "21 September 1979",
     "birthDate": "1979-09-21",
     "leaguePlayerId": "1184",
     "appearances": 431
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/appearances?comps=1&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 32 on page 1",
     "quote": "\"label\":\"21 September 1979\"},\"country\":{\"isoCode\":\"IE\",\"country\":\"Ireland\",\"demonym\":\"Irish\"}},\"age\":\"46 years 346 days\",\"name\":{\"display\":\"Richard Dunne\"",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "John Arne Riise",
    "value": 1980,
    "context": "Norwegian defender, 321 Premier League appearances",
    "detail": {
     "nameRaw": "John Arne Riise",
     "born": "24 September 1980",
     "birthDate": "1980-09-24",
     "leaguePlayerId": "2110",
     "appearances": 321
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/appearances?comps=1&pageSize=100&page=1",
     "page": "the league feed, one hundred rows a page; this row is rank 123 on page 2",
     "quote": "\"label\":\"24 September 1980\"},\"country\":{\"isoCode\":\"NO\",\"country\":\"Norway\",\"demonym\":\"Norwegian\"},\"place\":\"Ålesund\"},\"age\":\"45 years 343 days\",\"name\":{\"display\":\"John Arne Riise\"",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Lukasz Fabianski",
    "value": 1985,
    "context": "Polish goalkeeper, 376 Premier League appearances",
    "detail": {
     "nameRaw": "Lukasz Fabianski",
     "born": "18 April 1985",
     "birthDate": "1985-04-18",
     "leaguePlayerId": "3309",
     "appearances": 376
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/appearances?comps=1&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 62 on page 1",
     "quote": "\"label\":\"18 April 1985\"},\"country\":{\"isoCode\":\"PL\",\"country\":\"Poland\",\"demonym\":\"Polish\"},\"place\":\"Kostrzyn nad Odra\"},\"age\":\"41 years 137 days\",\"name\":{\"display\":\"Lukasz Fabianski\"",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Kevin Nolan",
    "value": 1982,
    "context": "English midfielder, 401 Premier League appearances",
    "detail": {
     "nameRaw": "Kevin Nolan",
     "born": "24 June 1982",
     "birthDate": "1982-06-24",
     "leaguePlayerId": "2040",
     "appearances": 401
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/appearances?comps=1&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 44 on page 1",
     "quote": "\"label\":\"24 June 1982\"},\"country\":{\"isoCode\":\"GB-ENG\",\"country\":\"England\",\"demonym\":\"English\"}},\"age\":\"44 years 70 days\",\"name\":{\"display\":\"Kevin Nolan\"",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Danny Murphy",
    "value": 1977,
    "context": "English midfielder, 417 Premier League appearances",
    "detail": {
     "nameRaw": "Danny Murphy",
     "born": "18 March 1977",
     "birthDate": "1977-03-18",
     "leaguePlayerId": "1423",
     "appearances": 417
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/appearances?comps=1&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 37 on page 1",
     "quote": "\"label\":\"18 March 1977\"},\"country\":{\"isoCode\":\"GB-ENG\",\"country\":\"England\",\"demonym\":\"English\"}},\"age\":\"49 years 168 days\",\"name\":{\"display\":\"Danny Murphy\"",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Roy Keane",
    "value": 1971,
    "context": "Irish midfielder, 366 Premier League appearances",
    "detail": {
     "nameRaw": "Roy Keane",
     "born": "10 August 1971",
     "birthDate": "1971-08-10",
     "leaguePlayerId": "407",
     "appearances": 366
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/appearances?comps=1&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 69 on page 1",
     "quote": "\"label\":\"10 August 1971\"},\"country\":{\"isoCode\":\"IE\",\"country\":\"Ireland\",\"demonym\":\"Irish\"}},\"age\":\"55 years 23 days\",\"name\":{\"display\":\"Roy Keane\"",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Les Ferdinand",
    "value": 1966,
    "context": "English forward, 351 Premier League appearances",
    "detail": {
     "nameRaw": "Les Ferdinand",
     "born": "8 December 1966",
     "birthDate": "1966-12-08",
     "leaguePlayerId": "462",
     "appearances": 351
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/appearances?comps=1&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 83 on page 1",
     "quote": "\"label\":\"8 December 1966\"},\"country\":{\"isoCode\":\"GB-ENG\",\"country\":\"England\",\"demonym\":\"English\"}},\"age\":\"59 years 268 days\",\"name\":{\"display\":\"Les Ferdinand\"",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Darren Anderton",
    "value": 1972,
    "context": "English midfielder, 319 Premier League appearances",
    "detail": {
     "nameRaw": "Darren Anderton",
     "born": "3 March 1972",
     "birthDate": "1972-03-03",
     "leaguePlayerId": "566",
     "appearances": 319
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/appearances?comps=1&pageSize=100&page=1",
     "page": "the league feed, one hundred rows a page; this row is rank 126 on page 2",
     "quote": "\"label\":\"3 March 1972\"},\"country\":{\"isoCode\":\"GB-ENG\",\"country\":\"England\",\"demonym\":\"English\"}},\"age\":\"54 years 183 days\",\"name\":{\"display\":\"Darren Anderton\"",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   }
  ],
  "direction": {
   "higher": "Younger",
   "lower": "Older"
  },
  "sourceLine": "Source: Premier League official player records (premierleague.com), read 2026-09-02.",
  "maxCallFraction": 0.4
 },
 {
  "id": "1016",
  "category": "England caps",
  "subtitle": "Senior England appearances. Retired players only, so nothing moves.",
  "unit": "count",
  "valueClass": "retired-only",
  "trueAsOf": "2026-09-02",
  "chain": [
   {
    "name": "Tony Adams",
    "value": 66,
    "context": "Defender, England debut 1987",
    "retired": true,
    "detail": {
     "nameRaw": "Tony Adams",
     "born": null,
     "debutYear": 1987,
     "caps": 66,
     "goals": 5
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Tony Adams DF 66 5 18 February 1987 Spain 7 October 2000 Germany [80][81]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Michael Owen",
    "value": 89,
    "context": "Forward, England debut 1998",
    "retired": true,
    "detail": {
     "nameRaw": "Michael Owen",
     "born": null,
     "debutYear": 1998,
     "caps": 89,
     "goals": 40
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Michael Owen FW 89 40 11 February 1998 Chile 26 March 2008 France [40][41]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "David Beckham",
    "value": 115,
    "context": "Midfielder, England debut 1996, born 1975",
    "retired": true,
    "detail": {
     "nameRaw": "David Beckham",
     "born": "02 May 1975",
     "debutYear": 1996,
     "caps": 115,
     "goals": 17
    },
    "source": {
     "publisher": "The FA (englandfootball.com)",
     "url": "https://www.englandfootball.com/england/mens-senior-team/squad/Legends-profiles/David-Beckham",
     "quote": "David Beckham won 115 caps for the England national team, making his debut in September 1996 against Moldova in the Three Lions' first game after Euro 96.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Bryan Robson",
    "value": 90,
    "context": "Retired England international",
    "retired": true,
    "detail": {
     "nameRaw": "Bryan Robson",
     "born": null,
     "debutYear": null,
     "caps": 90,
     "goals": null
    },
    "source": {
     "publisher": "The FA (englandfootball.com)",
     "url": "https://www.englandfootball.com/articles/2022/Aug/22/england-mens-senior-all-time-record-appearances-international-caps",
     "quote": "12 - Bryan Robson - 90 appearances",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Joe Hart",
    "value": 75,
    "context": "Goalkeeper, England debut 2008",
    "retired": true,
    "detail": {
     "nameRaw": "Joe Hart",
     "born": null,
     "debutYear": 2008,
     "caps": 75,
     "goals": 0
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Joe Hart GK 75 0 1 June 2008 Trinidad and Tobago 14 November 2017 Brazil [70][71]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Peter Beardsley",
    "value": 59,
    "context": "Forward, England debut 1986",
    "retired": true,
    "detail": {
     "nameRaw": "Peter Beardsley",
     "born": null,
     "debutYear": 1986,
     "caps": 59,
     "goals": 9
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Peter Beardsley FW 59 9 29 January 1986 Egypt 23 May 1996 China [108][109]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Paul Scholes",
    "value": 66,
    "context": "Midfielder, England debut 1997",
    "retired": true,
    "detail": {
     "nameRaw": "Paul Scholes",
     "born": null,
     "debutYear": 1997,
     "caps": 66,
     "goals": 14
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Paul Scholes MF 66 14 24 May 1997 South Africa 24 June 2004 Portugal [82][83]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Teddy Sheringham",
    "value": 51,
    "context": "Forward, England debut 1993",
    "retired": true,
    "detail": {
     "nameRaw": "Teddy Sheringham",
     "born": null,
     "debutYear": 1993,
     "caps": 51,
     "goals": 11
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Teddy Sheringham FW 51 11 29 May 1993 Poland 21 June 2002 Brazil [146][147]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Jermain Defoe",
    "value": 57,
    "context": "Forward, England debut 2004",
    "retired": true,
    "detail": {
     "nameRaw": "Jermain Defoe",
     "born": null,
     "debutYear": 2004,
     "caps": 57,
     "goals": 20
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Jermain Defoe FW 57 20 31 March 2004 Sweden 10 June 2017 Scotland [120][121]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Mark Wright",
    "value": 45,
    "context": "Defender, England debut 1984",
    "retired": true,
    "detail": {
     "nameRaw": "Mark Wright",
     "born": null,
     "debutYear": 1984,
     "caps": 45,
     "goals": 1
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Mark Wright DF 45 1 2 May 1984 Wales 18 May 1996 Hungary [170][171]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Paul Ince",
    "value": 53,
    "context": "Midfielder, England debut 1992",
    "retired": true,
    "detail": {
     "nameRaw": "Paul Ince",
     "born": null,
     "debutYear": 1992,
     "caps": 53,
     "goals": 2
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Paul Ince MF 53 2 9 September 1992 Spain 20 June 2000 Romania [138][139]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Emile Heskey",
    "value": 62,
    "context": "Forward, England debut 1999",
    "retired": true,
    "detail": {
     "nameRaw": "Emile Heskey",
     "born": null,
     "debutYear": 1999,
     "caps": 62,
     "goals": 7
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Emile Heskey FW 62 7 28 April 1999 Hungary 27 June 2010 Germany [100][101]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   }
  ],
  "sourceLine": "Source: The FA's official England legend profiles (englandfootball.com), opened 2 September 2026.",
  "nearTieMax": 0,
  "maxCallFraction": 0.4
 },
 {
  "id": "1000",
  "category": "West Bromwich Albion Premier League goals",
  "subtitle": "Most Premiership goals as at 14 September 2026",
  "unit": "count",
  "valueClass": "snapshot",
  "trueAsOf": "2026-09-14",
  "chain": [
   {
    "name": "Marc-Antoine Fortune",
    "value": 11,
    "context": "French forward, born 1981",
    "detail": {
     "nameRaw": "Marc-Antoine Fortuné",
     "born": "2 July 1981",
     "nationalTeam": "France",
     "position": "F",
     "leaguePlayerId": "3754",
     "club": "West Bromwich Albion",
     "sequence": 13,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 13 on page 1",
     "quote": "\"display\":\"Marc-Antoine Fortuné\",\"first\":\"Marc-Antoine\",\"last\":\"Fortuné\"},\"id\":3754,\"altIds\":{\"opta\":\"p14279\"}},\"rank\":13,\"name\":\"goals\",\"value\":11",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Gareth McAuley",
    "value": 15,
    "context": "Northern Irish defender, born 1979",
    "detail": {
     "nameRaw": "Gareth McAuley",
     "born": "5 December 1979",
     "nationalTeam": "Northern Ireland",
     "position": "D",
     "leaguePlayerId": "4437",
     "club": "West Bromwich Albion",
     "sequence": 8,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 8 on page 1",
     "quote": "\"display\":\"Gareth McAuley\",\"first\":\"Gareth\",\"last\":\"McAuley\"},\"id\":4437,\"altIds\":{\"opta\":\"p19272\"}},\"rank\":8,\"name\":\"goals\",\"value\":15",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Chris Brunt",
    "value": 24,
    "context": "Northern Irish midfielder, born 1984",
    "detail": {
     "nameRaw": "Chris Brunt",
     "born": "14 December 1984",
     "nationalTeam": "Northern Ireland",
     "position": "M",
     "leaguePlayerId": "3744",
     "club": "West Bromwich Albion",
     "sequence": 3,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 3 on page 1",
     "quote": "\"display\":\"Chris Brunt\",\"first\":\"Chris\",\"last\":\"Brunt\"},\"id\":3744,\"altIds\":{\"opta\":\"p19151\"}},\"rank\":3,\"name\":\"goals\",\"value\":24",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Peter Odemwingie",
    "value": 30,
    "context": "Nigerian forward, born 1981",
    "detail": {
     "nameRaw": "Peter Odemwingie",
     "born": "15 July 1981",
     "nationalTeam": "Nigeria",
     "position": "F",
     "leaguePlayerId": "4204",
     "club": "West Bromwich Albion",
     "sequence": 1,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 1 on page 1",
     "quote": "\"display\":\"Peter Odemwingie\",\"first\":\"Peter\",\"middle\":\"Osaze\",\"last\":\"Odemwingie\"},\"id\":4204,\"altIds\":{\"opta\":\"p26900\"}},\"rank\":1,\"name\":\"goals\",\"value\":30",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Salomon Rondon",
    "value": 24,
    "context": "Venezuelan forward, born 1989",
    "detail": {
     "nameRaw": "Salomón Rondón",
     "born": "16 September 1989",
     "nationalTeam": "Venezuela",
     "position": "F",
     "leaguePlayerId": "6030",
     "club": "West Bromwich Albion",
     "sequence": 3,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 3 on page 1",
     "quote": "\"display\":\"Salomón Rondón\",\"first\":\"Salomón\",\"last\":\"Rondón\"},\"id\":6030,\"altIds\":{\"opta\":\"p57134\"}},\"rank\":3,\"name\":\"goals\",\"value\":24",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "James Morrison",
    "value": 29,
    "context": "Scottish midfielder, born 1986",
    "detail": {
     "nameRaw": "James Morrison",
     "born": "25 May 1986",
     "nationalTeam": "Scotland",
     "position": "M",
     "leaguePlayerId": "2529",
     "club": "West Bromwich Albion",
     "sequence": 2,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 2 on page 1",
     "quote": "\"display\":\"James Morrison\",\"first\":\"James\",\"last\":\"Morrison\"},\"id\":2529,\"altIds\":{\"opta\":\"p18008\"}},\"rank\":2,\"name\":\"goals\",\"value\":29",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Romelu Lukaku",
    "value": 17,
    "context": "Belgian forward, born 1993",
    "detail": {
     "nameRaw": "Romelu Lukaku",
     "born": "13 May 1993",
     "nationalTeam": "Belgium",
     "position": "F",
     "leaguePlayerId": "4290",
     "club": "West Bromwich Albion",
     "sequence": 7,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 7 on page 1",
     "quote": "\"display\":\"Romelu Lukaku\",\"first\":\"Romelu\",\"last\":\"Lukaku\"},\"id\":4290,\"altIds\":{\"opta\":\"p66749\"}},\"rank\":7,\"name\":\"goals\",\"value\":17",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Zoltan Gera",
    "value": 12,
    "context": "Hungarian midfielder, born 1979",
    "detail": {
     "nameRaw": "Zoltán Gera",
     "born": "22 April 1979",
     "nationalTeam": "Hungary",
     "position": "M",
     "leaguePlayerId": "2390",
     "club": "West Bromwich Albion",
     "sequence": 9,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 9 on page 1",
     "quote": "\"display\":\"Zoltán Gera\",\"first\":\"Zoltán\",\"last\":\"Gera\"},\"id\":2390,\"altIds\":{\"opta\":\"p18430\"}},\"rank\":9,\"name\":\"goals\",\"value\":12",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Saido Berahino",
    "value": 23,
    "context": "Burundian forward, born 1993",
    "detail": {
     "nameRaw": "Saido Berahino",
     "born": "4 August 1993",
     "nationalTeam": "Burundi",
     "position": "F",
     "leaguePlayerId": "4205",
     "club": "West Bromwich Albion",
     "sequence": 5,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 5 on page 1",
     "quote": "\"display\":\"Saido Berahino\",\"first\":\"Saido\",\"last\":\"Berahino\"},\"id\":4205,\"altIds\":{\"opta\":\"p91972\"}},\"rank\":5,\"name\":\"goals\",\"value\":23",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Craig Dawson",
    "value": 12,
    "context": "English defender, born 1990",
    "detail": {
     "nameRaw": "Craig Dawson",
     "born": "6 May 1990",
     "nationalTeam": "England",
     "position": "D",
     "leaguePlayerId": "4198",
     "club": "West Bromwich Albion",
     "sequence": 9,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 9 on page 1",
     "quote": "\"display\":\"Craig Dawson\",\"first\":\"Craig\",\"last\":\"Dawson\"},\"id\":4198,\"altIds\":{\"opta\":\"p60232\"}},\"rank\":9,\"name\":\"goals\",\"value\":12",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Shane Long",
    "value": 19,
    "context": "Irish forward, born 1987",
    "detail": {
     "nameRaw": "Shane Long",
     "born": "22 January 1987",
     "nationalTeam": "Ireland",
     "position": "F",
     "leaguePlayerId": "3206",
     "club": "West Bromwich Albion",
     "sequence": 6,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 6 on page 1",
     "quote": "\"display\":\"Shane Long\",\"first\":\"Shane\",\"middle\":\"Patrick\",\"last\":\"Long\"},\"id\":3206,\"altIds\":{\"opta\":\"p20452\"}},\"rank\":6,\"name\":\"goals\",\"value\":19",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Robert Earnshaw",
    "value": 12,
    "context": "Welsh forward, born 1981",
    "detail": {
     "nameRaw": "Robert Earnshaw",
     "born": "6 April 1981",
     "nationalTeam": "Wales",
     "position": "F",
     "leaguePlayerId": "2819",
     "club": "West Bromwich Albion",
     "sequence": 9,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 9 on page 1",
     "quote": "\"display\":\"Robert Earnshaw\",\"first\":\"Robert\",\"last\":\"Earnshaw\"},\"id\":2819,\"altIds\":{\"opta\":\"p3227\"}},\"rank\":9,\"name\":\"goals\",\"value\":12",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   }
  ],
  "sourceLine": "Source: Premier League official statistics (premierleague.com), the club's ranked list, as at 14 September 2026.",
  "sequenceStep": 5,
  "nearTieMax": 0,
  "flipGuard": {
   "serve": "2026-10-12",
   "trueAsOf": "2026-09-14",
   "gamesBeforeServe": 2,
   "perGame": 0.75,
   "gain": 1
  }
 }
];
export const HL_SAMPLE_SCHEDULE = {
 "2026-09-18": "1015",
 "2026-09-19": "1016"
};
