/* hl-sample.js — GENERATED by tools/import_hilo.js. Do not edit.
 *
 * Three real boards and the two calendar days they stand on: what the Worker
 * falls back to with no database bound, and what the suites play. The bank
 * lives outside the repository; this is a sample of it, and small on purpose
 * so committing the bank by accident would show in a diff. */
export const HL_SAMPLE_BOARDS = [
 {
  "id": "398",
  "category": "Clubs by year formed",
  "subtitle": "The year the club was founded, under whatever name it started with.",
  "unit": "year",
  "valueClass": "fixed-by-nature",
  "trueAsOf": "2026-09-02",
  "chain": [
   {
    "name": "Wrexham",
    "value": 1864,
    "context": "Formed by Wrexham Cricket Club members at the Turf Hotel",
    "source": {
     "publisher": "Wrexham",
     "url": "https://www.wrexhamafc.co.uk/the-club/history-and-honours",
     "quote": "Wrexham AFC was founded in 1864, making it Wales' oldest professional Football Club and the third oldest in the world.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Barnsley",
    "value": 1887,
    "context": "Reverend Tiverton Preedy's Barnsley St. Peter's",
    "source": {
     "publisher": "Barnsley",
     "url": "https://www.barnsleyfc.co.uk/club/history/through-the-years",
     "quote": "The club was founded in 1887 by Reverend Tiverton Preedy, initially named Barnsley St. Peter's.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Southampton",
    "value": 1885,
    "context": "Formed by the St Mary's Church Young Men's Association",
    "source": {
     "publisher": "Southampton",
     "url": "https://www.southamptonfc.com/en/st-marys-fc",
     "quote": "The Saints were formed at a meeting of the St Mary's Church of England Young Men's Association sometime in November 1885.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Bradford City",
    "value": 1903,
    "context": "Forerunner Manningham FC played rugby at Valley Parade",
    "source": {
     "publisher": "Bradford City",
     "url": "https://www.bradfordcityafc.com/club/history/club-history",
     "quote": "1903: Manningham FC convert to football from rugby, secure election to the Football League and recruit players for a new team - 'Bradford City AFC'",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Charlton Athletic",
    "value": 1905,
    "context": "Formed by teenagers who played in East Street",
    "source": {
     "publisher": "Charlton Athletic",
     "url": "https://www.cafc.co.uk/history/mens-club-history/1905-1923-early-days",
     "quote": "On June 9th, 1905, a group of teenagers who once kicked a ball around that very street decided to get together and form a fully-fledged football club that was to become Charlton Athletic.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Brentford",
    "value": 1889,
    "context": "Formed at the Oxford and Cambridge Public House",
    "source": {
     "publisher": "Brentford",
     "url": "https://www.brentfordfc.com/en/history",
     "quote": "The formation of Brentford Football Club in 1889 is owed to the decision by the Brentford Local Board [a forerunner of today's councils] to open a new Recreation Ground in the town.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Stockport County",
    "value": 1883,
    "context": "Heaton Norris Rovers, the Hatters of Edgeley Park",
    "source": {
     "publisher": "Stockport County",
     "url": "https://www.stockportcounty.com/club/history/story",
     "quote": "Established in 1883 as Heaton Norris Rovers, in 1890 the name was changed to Stockport County to reflect the town gaining County Borough status.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "West Bromwich Albion",
    "value": 1878,
    "context": "Began as West Bromwich Strollers",
    "source": {
     "publisher": "West Bromwich Albion",
     "url": "https://www.wba.co.uk/club/history/club-history",
     "quote": "The club that became West Bromwich Albion was formed in 1878 by a group of young workers at the George Salter Springs factory, appropriate for a club whose terrace celebration would more than a century later become \"boing boing\".",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "West Ham United",
    "value": 1895,
    "context": "Began as Thames Ironworks, the shipyard's team",
    "source": {
     "publisher": "West Ham United",
     "url": "https://www.whufc.com/en/the-club/history/club-history/1890s",
     "quote": "In June 1895, the formation of the senior works football club was announced in the company's 'Thames Iron Works Gazette' newspaper and Taylor set about assembling a squad and arranging friendly matches for the 1895/96 season.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Aston Villa",
    "value": 1874,
    "context": "Four men from the chapel Bible class, under a gas lamp",
    "source": {
     "publisher": "Aston Villa",
     "url": "https://www.avfc.co.uk/history/timeline",
     "quote": "Four gentlemen stood under a gas lamp in Heathfield Road in 1874 and engaged in a discussion which would create one of the greatest clubs in the world.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Leicester City",
    "value": 1884,
    "context": "Known as Leicester Fosse until 1919",
    "source": {
     "publisher": "Leicester City",
     "url": "https://www.lcfc.com/history",
     "quote": "Formed in 1884, Leicester City Football Club, formerly known as Leicester Fosse until 1919, have won every major honour in English football.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   },
   {
    "name": "Colchester United",
    "value": 1937,
    "context": "Layer Road, then the JobServe Community Stadium",
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/Colchester_United_F.C.",
     "quote": "Founded in 1937, the club spent its early years playing in the Southern Football League until they were elected to the Football League in 1950.",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/founding-colchester-united-secondary.html"
    },
    "sourceNote": "the club's own site states no founding year; taken from the league's official club page"
   }
  ],
  "direction": {
   "higher": "Later",
   "lower": "Earlier"
  },
  "sourceLine": "Source: each club's own official website, opened 2 September 2026. Leeds from the Premier League's club page."
 },
 {
  "id": "399",
  "category": "England caps",
  "subtitle": "Senior England appearances. Retired players only, so nothing moves.",
  "unit": "count",
  "valueClass": "retired-only",
  "trueAsOf": "2026-09-02",
  "chain": [
   {
    "name": "Chris Woods",
    "value": 43,
    "context": "Goalkeeper, England debut 1985",
    "retired": true,
    "detail": {
     "nameRaw": "Chris Woods",
     "born": null,
     "debutYear": 1985,
     "caps": 43,
     "goals": 0
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Chris Woods GK 43 0 16 June 1985 United States 9 June 1993 United States [174][175]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Joe Hart",
    "value": 75,
    "context": "Goalkeeper, England debut 2008",
    "retired": true,
    "detail": {
     "nameRaw": "Joe Hart",
     "born": null,
     "debutYear": 2008,
     "caps": 75,
     "goals": 0
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Joe Hart GK 75 0 1 June 2008 Trinidad and Tobago 14 November 2017 Brazil [70][71]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Sol Campbell",
    "value": 73,
    "context": "Defender, England debut 1996",
    "retired": true,
    "detail": {
     "nameRaw": "Sol Campbell",
     "born": null,
     "debutYear": 1996,
     "caps": 73,
     "goals": 1
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Sol Campbell DF 73 1 18 May 1996 Hungary 21 November 2007 Croatia [74][75]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Emile Heskey",
    "value": 62,
    "context": "Forward, England debut 1999",
    "retired": true,
    "detail": {
     "nameRaw": "Emile Heskey",
     "born": null,
     "debutYear": 1999,
     "caps": 62,
     "goals": 7
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Emile Heskey FW 62 7 28 April 1999 Hungary 27 June 2010 Germany [100][101]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "James Milner",
    "value": 61,
    "context": "Midfielder / Defender, England debut 2009",
    "retired": true,
    "detail": {
     "nameRaw": "James Milner",
     "born": null,
     "debutYear": 2009,
     "caps": 61,
     "goals": 1
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "James Milner MF / DF 61 1 12 August 2009 Netherlands 11 June 2016 Russia [104][105]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "John Terry",
    "value": 78,
    "context": "Defender, England debut 2003",
    "retired": true,
    "detail": {
     "nameRaw": "John Terry",
     "born": null,
     "debutYear": 2003,
     "caps": 78,
     "goals": 6
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "John Terry DF 78 6 3 June 2003 Serbia and Montenegro 7 September 2012 Moldova [60][61]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Phil Jagielka",
    "value": 40,
    "context": "Defender, England debut 2008",
    "retired": true,
    "detail": {
     "nameRaw": "Phil Jagielka",
     "born": null,
     "debutYear": 2008,
     "caps": 40,
     "goals": 3
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Phil Jagielka DF 40 3 1 June 2008 Trinidad and Tobago 15 November 2016 Spain [198][199]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Jermain Defoe",
    "value": 57,
    "context": "Forward, England debut 2004",
    "retired": true,
    "detail": {
     "nameRaw": "Jermain Defoe",
     "born": null,
     "debutYear": 2004,
     "caps": 57,
     "goals": 20
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Jermain Defoe FW 57 20 31 March 2004 Sweden 10 June 2017 Scotland [120][121]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Tony Adams",
    "value": 66,
    "context": "Defender, England debut 1987",
    "retired": true,
    "detail": {
     "nameRaw": "Tony Adams",
     "born": null,
     "debutYear": 1987,
     "caps": 66,
     "goals": 5
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Tony Adams DF 66 5 18 February 1987 Spain 7 October 2000 Germany [80][81]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Paul Ince",
    "value": 53,
    "context": "Midfielder, England debut 1992",
    "retired": true,
    "detail": {
     "nameRaw": "Paul Ince",
     "born": null,
     "debutYear": 1992,
     "caps": 53,
     "goals": 2
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Paul Ince MF 53 2 9 September 1992 Spain 20 June 2000 Romania [138][139]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Paul Robinson",
    "value": 41,
    "context": "Goalkeeper, England debut 2003",
    "retired": true,
    "detail": {
     "nameRaw": "Paul Robinson",
     "born": null,
     "debutYear": 2003,
     "caps": 41,
     "goals": 0
    },
    "source": {
     "publisher": "Secondary source",
     "url": "https://en.wikipedia.org/wiki/List_of_England_international_footballers",
     "quote": "Paul Robinson GK 41 0 12 February 2003 Australia 17 October 2007 Russia [196][197]",
     "accessed": "2026-09-02",
     "tier": "secondary",
     "cached": "bank/sources/england-caps-secondary.html"
    }
   },
   {
    "name": "Wayne Rooney",
    "value": 120,
    "context": "Forward, England debut 2003, born 1985",
    "retired": true,
    "detail": {
     "nameRaw": "Wayne Rooney",
     "born": "24 October 1985",
     "debutYear": 2003,
     "caps": 120,
     "goals": 53
    },
    "source": {
     "publisher": "The FA (englandfootball.com)",
     "url": "https://www.englandfootball.com/england/mens-senior-team/squad/Legends-profiles/wayne-rooney",
     "quote": "Wayne Rooney won 120 caps for England between 2003 and 2018, a record for an outfield player in the history of the English national team.",
     "accessed": "2026-09-02",
     "tier": "official"
    }
   }
  ],
  "sourceLine": "Source: The FA's official England legend profiles (englandfootball.com), opened 2 September 2026."
 },
 {
  "id": "1000",
  "category": "West Bromwich Albion Premier League goals",
  "subtitle": "Most Premiership goals as at 14 September 2026",
  "unit": "count",
  "valueClass": "snapshot",
  "trueAsOf": "2026-09-14",
  "chain": [
   {
    "name": "Marc-Antoine Fortune",
    "value": 11,
    "context": "French forward, born 1981",
    "detail": {
     "nameRaw": "Marc-Antoine Fortuné",
     "born": "2 July 1981",
     "nationalTeam": "France",
     "position": "F",
     "leaguePlayerId": "3754",
     "club": "West Bromwich Albion",
     "sequence": 13,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 13 on page 1",
     "quote": "\"display\":\"Marc-Antoine Fortuné\",\"first\":\"Marc-Antoine\",\"last\":\"Fortuné\"},\"id\":3754,\"altIds\":{\"opta\":\"p14279\"}},\"rank\":13,\"name\":\"goals\",\"value\":11",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Gareth McAuley",
    "value": 15,
    "context": "Northern Irish defender, born 1979",
    "detail": {
     "nameRaw": "Gareth McAuley",
     "born": "5 December 1979",
     "nationalTeam": "Northern Ireland",
     "position": "D",
     "leaguePlayerId": "4437",
     "club": "West Bromwich Albion",
     "sequence": 8,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 8 on page 1",
     "quote": "\"display\":\"Gareth McAuley\",\"first\":\"Gareth\",\"last\":\"McAuley\"},\"id\":4437,\"altIds\":{\"opta\":\"p19272\"}},\"rank\":8,\"name\":\"goals\",\"value\":15",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Chris Brunt",
    "value": 24,
    "context": "Northern Irish midfielder, born 1984",
    "detail": {
     "nameRaw": "Chris Brunt",
     "born": "14 December 1984",
     "nationalTeam": "Northern Ireland",
     "position": "M",
     "leaguePlayerId": "3744",
     "club": "West Bromwich Albion",
     "sequence": 3,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 3 on page 1",
     "quote": "\"display\":\"Chris Brunt\",\"first\":\"Chris\",\"last\":\"Brunt\"},\"id\":3744,\"altIds\":{\"opta\":\"p19151\"}},\"rank\":3,\"name\":\"goals\",\"value\":24",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Peter Odemwingie",
    "value": 30,
    "context": "Nigerian forward, born 1981",
    "detail": {
     "nameRaw": "Peter Odemwingie",
     "born": "15 July 1981",
     "nationalTeam": "Nigeria",
     "position": "F",
     "leaguePlayerId": "4204",
     "club": "West Bromwich Albion",
     "sequence": 1,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 1 on page 1",
     "quote": "\"display\":\"Peter Odemwingie\",\"first\":\"Peter\",\"middle\":\"Osaze\",\"last\":\"Odemwingie\"},\"id\":4204,\"altIds\":{\"opta\":\"p26900\"}},\"rank\":1,\"name\":\"goals\",\"value\":30",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Salomon Rondon",
    "value": 24,
    "context": "Venezuelan forward, born 1989",
    "detail": {
     "nameRaw": "Salomón Rondón",
     "born": "16 September 1989",
     "nationalTeam": "Venezuela",
     "position": "F",
     "leaguePlayerId": "6030",
     "club": "West Bromwich Albion",
     "sequence": 3,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 3 on page 1",
     "quote": "\"display\":\"Salomón Rondón\",\"first\":\"Salomón\",\"last\":\"Rondón\"},\"id\":6030,\"altIds\":{\"opta\":\"p57134\"}},\"rank\":3,\"name\":\"goals\",\"value\":24",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "James Morrison",
    "value": 29,
    "context": "Scottish midfielder, born 1986",
    "detail": {
     "nameRaw": "James Morrison",
     "born": "25 May 1986",
     "nationalTeam": "Scotland",
     "position": "M",
     "leaguePlayerId": "2529",
     "club": "West Bromwich Albion",
     "sequence": 2,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 2 on page 1",
     "quote": "\"display\":\"James Morrison\",\"first\":\"James\",\"last\":\"Morrison\"},\"id\":2529,\"altIds\":{\"opta\":\"p18008\"}},\"rank\":2,\"name\":\"goals\",\"value\":29",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Romelu Lukaku",
    "value": 17,
    "context": "Belgian forward, born 1993",
    "detail": {
     "nameRaw": "Romelu Lukaku",
     "born": "13 May 1993",
     "nationalTeam": "Belgium",
     "position": "F",
     "leaguePlayerId": "4290",
     "club": "West Bromwich Albion",
     "sequence": 7,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 7 on page 1",
     "quote": "\"display\":\"Romelu Lukaku\",\"first\":\"Romelu\",\"last\":\"Lukaku\"},\"id\":4290,\"altIds\":{\"opta\":\"p66749\"}},\"rank\":7,\"name\":\"goals\",\"value\":17",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Zoltan Gera",
    "value": 12,
    "context": "Hungarian midfielder, born 1979",
    "detail": {
     "nameRaw": "Zoltán Gera",
     "born": "22 April 1979",
     "nationalTeam": "Hungary",
     "position": "M",
     "leaguePlayerId": "2390",
     "club": "West Bromwich Albion",
     "sequence": 9,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 9 on page 1",
     "quote": "\"display\":\"Zoltán Gera\",\"first\":\"Zoltán\",\"last\":\"Gera\"},\"id\":2390,\"altIds\":{\"opta\":\"p18430\"}},\"rank\":9,\"name\":\"goals\",\"value\":12",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Saido Berahino",
    "value": 23,
    "context": "Burundian forward, born 1993",
    "detail": {
     "nameRaw": "Saido Berahino",
     "born": "4 August 1993",
     "nationalTeam": "Burundi",
     "position": "F",
     "leaguePlayerId": "4205",
     "club": "West Bromwich Albion",
     "sequence": 5,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 5 on page 1",
     "quote": "\"display\":\"Saido Berahino\",\"first\":\"Saido\",\"last\":\"Berahino\"},\"id\":4205,\"altIds\":{\"opta\":\"p91972\"}},\"rank\":5,\"name\":\"goals\",\"value\":23",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Craig Dawson",
    "value": 12,
    "context": "English defender, born 1990",
    "detail": {
     "nameRaw": "Craig Dawson",
     "born": "6 May 1990",
     "nationalTeam": "England",
     "position": "D",
     "leaguePlayerId": "4198",
     "club": "West Bromwich Albion",
     "sequence": 9,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 9 on page 1",
     "quote": "\"display\":\"Craig Dawson\",\"first\":\"Craig\",\"last\":\"Dawson\"},\"id\":4198,\"altIds\":{\"opta\":\"p60232\"}},\"rank\":9,\"name\":\"goals\",\"value\":12",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Shane Long",
    "value": 19,
    "context": "Irish forward, born 1987",
    "detail": {
     "nameRaw": "Shane Long",
     "born": "22 January 1987",
     "nationalTeam": "Ireland",
     "position": "F",
     "leaguePlayerId": "3206",
     "club": "West Bromwich Albion",
     "sequence": 6,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 6 on page 1",
     "quote": "\"display\":\"Shane Long\",\"first\":\"Shane\",\"middle\":\"Patrick\",\"last\":\"Long\"},\"id\":3206,\"altIds\":{\"opta\":\"p20452\"}},\"rank\":6,\"name\":\"goals\",\"value\":19",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   },
   {
    "name": "Robert Earnshaw",
    "value": 12,
    "context": "Welsh forward, born 1981",
    "detail": {
     "nameRaw": "Robert Earnshaw",
     "born": "6 April 1981",
     "nationalTeam": "Wales",
     "position": "F",
     "leaguePlayerId": "2819",
     "club": "West Bromwich Albion",
     "sequence": 9,
     "canMove": false,
     "basis": "the league's own ranked list for the club as fetched on 14 September 2026; active players included, the value is fixed by its date"
    },
    "source": {
     "publisher": "Premier League",
     "url": "https://footballapi.pulselive.com/football/stats/ranked/players/goals?comps=1&teams=36&pageSize=100&page=0",
     "page": "the league feed, one hundred rows a page; this row is rank 9 on page 1",
     "quote": "\"display\":\"Robert Earnshaw\",\"first\":\"Robert\",\"last\":\"Earnshaw\"},\"id\":2819,\"altIds\":{\"opta\":\"p3227\"}},\"rank\":9,\"name\":\"goals\",\"value\":12",
     "accessed": "2026-09-14",
     "tier": "official"
    }
   }
  ],
  "sourceLine": "Source: Premier League official statistics (premierleague.com), the club's ranked list, as at 14 September 2026.",
  "sequenceStep": 5,
  "nearTieMax": 0,
  "flipGuard": {
   "serve": "2026-10-12",
   "trueAsOf": "2026-09-14",
   "gamesBeforeServe": 2,
   "perGame": 0.75,
   "gain": 1
  }
 }
];
export const HL_SAMPLE_SCHEDULE = {
 "2026-09-03": "398",
 "2026-09-04": "399"
};
