#!/usr/bin/env node
/* tools/build_scrambled_fr.js — the boards for Scrambled XI: Friends and
 * Vowels XI: Friends.
 *
 *   node tools/build_scrambled_fr.js             gate the bank, write the sample module
 *   node tools/build_scrambled_fr.js --check     gate, and refuse a module that has drifted
 *   node tools/build_scrambled_fr.js --sql       also write data/fr-sc-production.sql
 *   ... --source <folder>                        the bank (default ../Other/ScrambledXI_Friends/boards)
 *
 * THE SAME RULES AS FOOTBALL'S, IMPORTED. Every board goes through
 * build_scrambled.js's own build() and gate() -- the name shape, the letter
 * bags, the alias claims, the substring rule, both cyphers -- with `list` set,
 * which drops only the pitch: a Friends board is eleven answers under its
 * theme (the owner, 29 Sep 2026: "start the Friends Scrambled and Vowels
 * build"). Vowels XI: Friends reads the same boards, as football's does.
 *
 * THE BANK LIVES OUTSIDE THIS REPOSITORY, which is public. It is gated in full
 * when present and goes to D1 as fr_sc_board (migration 050) through --sql;
 * it is never written here. The committed module is built from four SAMPLE
 * sources written for the repository (functions/_lib/fr-sc-sample.js), so it
 * is the same on every machine and --check means the same thing in CI, which
 * has no bank.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "./build_scrambled.js";
import { readTextIfExists } from "./text.js";
import { FR_SC_SAMPLE } from "../functions/_lib/fr-sc-sample.js";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const arg = (k) => { const i = process.argv.indexOf(k); return i > -1 ? process.argv[i + 1] : null; };
const CHECK = process.argv.includes("--check");
const SQL = process.argv.includes("--sql");
const SOURCE = arg("--source") || path.join(ROOT, "..", "Other", "ScrambledXI_Friends", "boards");
const DEST = path.join(ROOT, "functions", "_lib", "fr-sc-boards.js");
/* FIVE ANSWERS A BOARD (the owner, 29 Sep 2026: "for this we dont need 11,
   we can have 3, 4 or 5 phrases or names or places etc", then "Always 5"). */
export const SIZE = 5;
const OUT = arg("--out") ? path.resolve(arg("--out")) : path.join(ROOT, "data", "fr-sc-production.sql");

/* A refusal is printed by build() itself; this only counts them, quietly. */
function buildAll(sources) {
  const built = [], refused = [];
  for (const [label, src] of sources) {
    const b = build(src, label, null, { list: true, size: SIZE });
    if (b) built.push(b); else refused.push(label);
  }
  return { built, refused };
}

/* ---- the sample, which is what the repository holds ---------------------- */

const sample = buildAll(FR_SC_SAMPLE.map((s) => ["sample board " + s.id, s]));
if (sample.refused.length) {
  console.error(`REFUSED: sample board(s) ${sample.refused.join(", ")} failed the gate. Nothing written.`);
  process.exit(1);
}
const module_ = `/* GENERATED by tools/build_scrambled_fr.js — do not edit by hand.
 *
 * A SAMPLE OF ${sample.built.length} BOARDS FOR SCRAMBLED XI: FRIENDS AND VOWELS XI: FRIENDS,
 * NOT THE BANK. The bank is in D1 (fr_sc_board) and its sources live outside
 * this repository. These are built from functions/_lib/fr-sc-sample.js, four
 * boards written for the repository and no day of the ring, so an unbound
 * database degrades to something playable rather than to nothing.
 *
 * Rebuild with:  node tools/build_scrambled_fr.js
 */
export const FR_SC_BOARDS = ${JSON.stringify(sample.built, null, 2)};
`;

/* ---- the bank, gated in full when it is here ------------------------------ */

let bank = null;
if (fs.existsSync(SOURCE)) {
  const files = fs.readdirSync(SOURCE).filter((f) => f.endsWith(".json") && !f.startsWith("_")).sort();
  const sources = files.map((f) => [f, JSON.parse(readTextIfExists(path.join(SOURCE, f)))]);
  bank = buildAll(sources);
  /* THE RING COUNTS BY ID, so the ids must be exactly 1..N: a gap is a day
     with no board, a duplicate is two boards claiming one day, and either
     would move every later day. */
  const ids = bank.built.map((b) => b.id).sort((a, b) => a - b);
  const want = ids.every((id, i) => id === i + 1);
  if (bank.refused.length || !want || ids.length !== files.length) {
    console.error(`REFUSED: ${bank.refused.length} board(s) failed the gate` +
      (want ? "" : `, and the ids are not 1..${ids.length} with no gap`) +
      (bank.refused.length ? ": " + bank.refused.slice(0, 8).join(", ") : "") + ". Nothing written.");
    process.exit(1);
  }
  const names = bank.built.reduce((n, b) => n + b.slots.length, 0);
  console.log(`  ${bank.built.length} boards gated from ${path.relative(ROOT, SOURCE) || SOURCE}, ${names} names`);
} else if (SQL) {
  console.error(`REFUSED: --sql needs the bank, and there is none at ${SOURCE}.`);
  process.exit(1);
} else {
  console.log("  no bank here (CI has none): the sample alone is gated");
}

/* ---- the module ----------------------------------------------------------- */

if (CHECK) {
  const stored = readTextIfExists(DEST) || "";
  if (stored !== module_) {
    console.error(`${path.relative(ROOT, DEST)} is NOT what the sample builds. Run: node tools/build_scrambled_fr.js`);
    process.exit(1);
  }
  console.log(`  ${sample.built.length} sample boards gated, and the stored module matches. Nothing written.`);
} else {
  fs.writeFileSync(DEST, module_);
  console.log(`  wrote ${path.relative(ROOT, DEST)} (${sample.built.length} sample boards)`);
}

/* ---- the production SQL, on request --------------------------------------- */

if (SQL && !CHECK) {
  const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
  const now = new Date().toISOString();
  const lines = [
    "-- GENERATED by tools/build_scrambled_fr.js --sql — do not edit.",
    "-- Every answer on every Friends Scrambled/Vowels board. SECRET: gitignored.",
    "-- Apply migration 050-friends-scrambled.sql first.",
    "",
  ];
  /* ONLY WHAT CHANGED IS WRITTEN: an upsert per board that writes where the
     board differs (updated_at moves with it, not on its own), and a board the
     bank no longer has is deleted by id. Re-importing the same bank writes
     nothing; D1 bills rows written, and emptying the table first wrote all 365
     every time. */
  for (const b of bank.built) {
    lines.push("INSERT INTO fr_sc_board (id, title, payload, source, updated_at) VALUES (" +
      [b.id, q(b.title), q(JSON.stringify(b)), q(b.source), q(now)].join(", ") + ")" +
      " ON CONFLICT(id) DO UPDATE SET title = excluded.title, payload = excluded.payload, source = excluded.source," +
      " updated_at = excluded.updated_at WHERE fr_sc_board.title IS NOT excluded.title" +
      " OR fr_sc_board.payload IS NOT excluded.payload OR fr_sc_board.source IS NOT excluded.source;");
  }
  lines.push(`DELETE FROM fr_sc_board WHERE id NOT IN (${bank.built.map((b) => b.id).join(", ")});`);
  lines.push("");
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, lines.join("\n"));
  console.log(`  wrote ${path.relative(ROOT, OUT) || OUT} (${bank.built.length} boards)`);
  console.log(`  apply with: npx wrangler d1 execute crosswordxi --remote --file=${path.relative(ROOT, OUT).split(path.sep).join("/")}`);
}
