/* import_hilo_test.mjs — the served-day guard, pinned.
 *
 * WHY THIS FILE EXISTS. Until 15 September 2026 tools/import_hilo.js had NO
 * served-day protection of any kind. Not a weak one — none. It takes the
 * calendar wholesale out of schedule.json, opens its SQL with
 *
 *     DELETE FROM hl_board;
 *     DELETE FROM hl_schedule;
 *
 * and rewrites every board and every day. It gates BOARDS carefully — shape,
 * duplicate ids, the calendar's own rules — and nothing at all guarded WHICH
 * DAY GETS WHICH BOARD, over a game that has been live since 3 September.
 *
 * Ballpark's and Grid's importers had a subtler form of the same fault, fixed
 * the same day: a comparison that was EMPTY rather than absent. This one was
 * found by going and checking the other importers for the shape rather than
 * waiting to be bitten, which is the whole return on naming a fault's shape.
 *
 * TWO QUESTIONS, AND THE SECOND IS THE ONE PEOPLE SKIP.
 *   Did the day change hands?   board 785 was Monday's; is it still Monday's.
 *   Did the board itself change? An id keeping its place does NOT mean the
 *   board is unchanged — Ballpark's bp-0014 and bp-0015 kept their ids while
 *   six of eleven questions moved off each. Every payload is rewritten here, so
 *   a served day can be replaced silently under an id that never moved.
 *
 * A FIXTURE, NOT THE BANK. These drive the exported functions with small maps,
 * so the suite runs on a machine with no HiLoXI beside it — which is every CI
 * runner. The live paths were exercised by hand against the real 282-board
 * source on the day the guard was written: served days swapped -> refused,
 * a served board's content edited under an unchanged id -> refused, a FUTURE
 * board edited -> permitted, the previous SQL removed -> refused.
 *
 *   node tools/import_hilo_test.mjs      (from the repo root)
 */
import { scheduleFromSql, boardRowsFromSql, servedClash, boardRow } from "./import_hilo.js";

let pass = 0, fail = 0;
const t = (n, ok, d) => { ok ? pass++ : fail++; console.log(`${ok ? "  ok  " : "FAIL  "}${n}${d ? "  — " + d : ""}`); };

const TODAY = "2026-09-15";

/* Rows as the writer emits them, minus the updated_at the guard strips. */
const row = (id, payload) =>
  `INSERT INTO hl_board (id, kind, club, category, subtitle, payload, updated_at) VALUES ` +
  `('${id}', 'daily', NULL, 'cat', 'sub', '${payload}'`;

console.log("Reading the previous calendar back out of its own SQL");
{
  const sql = [
    "-- GENERATED by tools/import_hilo.js — do not edit.",
    "DELETE FROM hl_board;",
    row("788", "{a:1}") + ", '2026-09-14T00:00:00Z');",
    "INSERT INTO hl_schedule (day, board_id) VALUES ('2026-09-10', '788');",
    "INSERT INTO hl_schedule (day, board_id) VALUES ('2026-09-20', '900');",
  ].join("\n");
  const s = scheduleFromSql(sql);
  t("every scheduled day is read back", Object.keys(s).length === 2, JSON.stringify(s));
  t("and each names its board", s["2026-09-10"] === "788" && s["2026-09-20"] === "900");
  const rows = boardRowsFromSql(sql);
  t("board rows are read back keyed by id", !!rows["788"], Object.keys(rows).join(","));
  /* THE STAMP MOVES ON EVERY RUN. If it were compared, every board would look
     changed on every import and the guard would be switched off within a week. */
  t("and the updated_at is not part of what is compared",
    rows["788"].indexOf("2026-09-14T00:00:00Z") === -1,
    "a timestamp that moves every run must not read as a changed board");
}

console.log("");
console.log("A day that has run may not change hands");
{
  const prevS = { "2026-09-10": "788", "2026-09-11": "789" };
  const prevR = { 788: row("788", "x"), 789: row("789", "y") };

  t("the same calendar is no clash",
    servedClash(prevS, prevR, prevS, prevR, TODAY).length === 0);

  const swapped = { "2026-09-10": "789", "2026-09-11": "788" };
  const c = servedClash(prevS, prevR, swapped, prevR, TODAY);
  t("two served days swapping boards is refused", c.length === 2,
    c.map((x) => x.day + ": " + x.why).join("; "));

  const gone = { "2026-09-10": "788" };
  t("a served day dropped from the calendar is refused too",
    servedClash(prevS, prevR, gone, prevR, TODAY).length === 1,
    "a played day with no board is the same lie told by omission");
}

console.log("");
console.log("And an id keeping its place is not the same as a board being unchanged");
{
  const prevS = { "2026-09-10": "788" };
  const prevR = { 788: row("788", "the board as it was served") };
  const nextR = { 788: row("788", "the board, quietly rebuilt") };

  const c = servedClash(prevS, prevR, prevS, nextR, TODAY);
  t("the same id with different content is refused", c.length === 1,
    c.length ? c[0].why : "nothing refused");
  t("and it says WHY, because the two causes have different fixes",
    c.length === 1 && /content changed/.test(c[0].why), c.length ? c[0].why : "");
}

console.log("");
console.log("But the future is what a re-import is for");
{
  const prevS = { "2026-09-10": "788", "2026-09-20": "900" };
  const prevR = { 788: row("788", "x"), 900: row("900", "old future board") };
  const nextS = { "2026-09-10": "788", "2026-09-20": "1015" };
  const nextR = { 788: row("788", "x"), 1015: row("1015", "a new future board") };

  t("a future day may change board entirely",
    servedClash(prevS, prevR, nextS, nextR, TODAY).length === 0,
    "rebuilding the run-in is the normal case and must not be blocked");

  const editedFuture = { 788: row("788", "x"), 900: row("900", "rewritten") };
  t("and a future board may be rewritten under its own id",
    servedClash(prevS, prevR, prevS, editedFuture, TODAY).length === 0);

  /* TODAY IS NOT THE FUTURE. A board being served right now has been served. */
  const todayS = { [TODAY]: "788" };
  t("today counts as played, not as future",
    servedClash(todayS, prevR, { [TODAY]: "900" }, nextR, TODAY).length === 1,
    "the day is half over by the time anybody runs this");
}

console.log("");
console.log("A row format written once");
{
  /* The writer built its INSERT inline, so the guard could only ever have
     compared against a second copy of the same formatting — two copies of a row
     format being two answers about whether a board changed. */
  const b = { id: "788", category: "cat", subtitle: "sub" };
  const a1 = boardRow(b, "stamp-one"), a2 = boardRow(b, "stamp-two");
  t("the same board gives the same row but for its stamp",
    a1.slice(0, a1.lastIndexOf(", '")) === a2.slice(0, a2.lastIndexOf(", '")));
  t("and a changed board gives a different one",
    boardRow({ ...b, subtitle: "other" }, "s") !== boardRow(b, "s"));
  /* An apostrophe in a club or category name must not end the string early. */
  const q = boardRow({ id: "1", category: "Nott'm Forest", subtitle: "s" }, "s");
  t("a quote in a name is escaped rather than breaking the row",
    q.indexOf("Nott''m Forest") > -1, "SQL doubles a quote to escape it");
}

console.log(`\n${pass} passed, ${fail} failed`);
if (fail) process.exit(1);
