/* node tools/import_wordsearch.js --source <the folder holding bank.json>
 *
 * --source IS REQUIRED, and there is no default. The default was
 * ../wordsearchxi-source, a folder that has never existed: the bank's real
 * home is the owner's OneDrive (Documents\GitHub\wordsearchxi-source, see
 * CLAUDE.md), and that dead default cost two days on Word Search and a morning
 * on QuickFire, because a path that lives only in a tool's default is a path
 * nobody can find. The owner, 3 Oct 2026: leave the bank in OneDrive. So this
 * asks rather than guesses.
 *
 * Reads bank.json (the 374 boards and the schedule, which live OUTSIDE the
 * repository — same rule as the crossword's clue bank: not ignored, absent)
 * and writes data/ws-production.sql for wrangler. The generated file contains
 * every answer and is gitignored; never commit it.
 *
 *   npx wrangler d1 execute crosswordxi --remote --file=data/ws-production.sql
 *
 * Re-run whenever a board changes — the eleven "evolving" boards are the
 * reason updates are a SQL import rather than a site deploy.
 */
import fs from "node:fs";
import path from "node:path";

const argIdx = process.argv.indexOf("--source");
const SRC = argIdx > -1 ? process.argv[argIdx + 1] : null;
if (!SRC) {
  console.error("REFUSED: --source <folder> is required. The word search bank is not in this repository;\n" +
    "on the owner's machine it is OneDrive\\Documents\\GitHub\\wordsearchxi-source (CLAUDE.md, The banks are secret).");
  process.exit(1);
}
const bankPath = path.join(SRC, "bank.json");
if (!fs.existsSync(bankPath)) {
  console.error(`No bank at ${bankPath}. The source folder is deliberately not in this repository.`);
  process.exit(1);
}
const bank = JSON.parse(fs.readFileSync(bankPath, "utf8"));
const { puzzles, schedule } = bank;

/* THE COORDINATE BOUNDARY. The source bank's placements are 1-based
   (rows 1-14, cols 1-12) — proven, not assumed: GOLDEN on XIWS-0001 starts
   at row 14. v4.3 survived this because its hit-testing matched selected
   STRINGS, so the placements only ever fed hints; this engine judges drags
   by cells, so the convention must be one thing everywhere. It becomes
   0-based HERE, once, and every consumer downstream — game, functions,
   tests — speaks 0-based. No -1 appears anywhere else in the family. */
const DIRS = { E:[0,1], W:[0,-1], S:[1,0], N:[-1,0], SE:[1,1], SW:[1,-1], NE:[-1,1], NW:[-1,-1] };
for (const p of puzzles) {
  for (const a of p.answers.concat([p.bonus])) {
    const pl = a.placement;
    pl.start_row -= 1; pl.start_col -= 1; pl.end_row -= 1; pl.end_col -= 1;
  }
}

/* The XI invariant is a build gate, not a hope. Refuse the whole import if
   any board breaks it — a bank that is 373 elevens and one ten is not a bank
   with one small problem, it is a brand claim that has stopped being true. */
let bad = 0;
for (const p of puzzles) {
  if (!Array.isArray(p.answers) || p.answers.length !== 11) { console.error(`${p.id}: ${p.answers?.length} answers, not 11`); bad++; }
  if (!p.bonus || !p.bonus.grid) { console.error(`${p.id}: no bonus`); bad++; }
  if (!Array.isArray(p.grid) || p.grid.length !== 14 || p.grid.some((r) => r.length !== 12)) { console.error(`${p.id}: grid is not 14x12`); bad++; }
  for (const a of p.answers.concat([p.bonus])) {
    if (!/^[A-Z]+$/.test(a.grid)) { console.error(`${p.id}: ${a.grid} is not plain A-Z`); bad++; }
    /* Every placement must spell its word off the grid — the guard that
       caught the coordinate base. A placement that does not spell its word
       is a board that cannot be completed, and it must never import. */
    const pl = a.placement, d = DIRS[pl.direction];
    if (!d) { console.error(`${p.id}: ${a.grid} has direction ${pl.direction}`); bad++; continue; }
    let word = "", off = false;
    for (let k = 0; k < a.grid.length; k++) {
      const r = pl.start_row + d[0] * k, c = pl.start_col + d[1] * k;
      if (r < 0 || r >= 14 || c < 0 || c >= 12) { off = true; break; }
      word += p.grid[r][c];
    }
    if (off || word !== a.grid) { console.error(`${p.id}: ${a.grid} placement spells ${off ? "off-grid" : word}`); bad++; }
    if (pl.end_row !== pl.start_row + d[0] * (a.grid.length - 1) ||
        pl.end_col !== pl.start_col + d[1] * (a.grid.length - 1)) {
      console.error(`${p.id}: ${a.grid} end coords disagree with start + length`); bad++;
    }
  }
}
const ids = new Set(puzzles.map((p) => p.id));
for (const [day, id] of Object.entries(schedule)) {
  if (!ids.has(id)) { console.error(`schedule ${day} names ${id}, not in bank`); bad++; }
}
if (bad) { console.error(`${bad} problems — nothing written.`); process.exit(1); }

const esc = (s) => String(s).replace(/'/g, "''");
const lines = [
  "-- Generated by tools/import_wordsearch.js. Contains every answer. NEVER COMMIT.",
  "DELETE FROM ws_schedule;",
  "DELETE FROM ws_puzzles;",
];
for (const p of puzzles) {
  const payload = JSON.stringify({ grid: p.grid, answers: p.answers, bonus: p.bonus });
  lines.push(
    `INSERT INTO ws_puzzles (id, theme, category, status, hash, version, share_key, payload) VALUES ` +
    `('${esc(p.id)}','${esc(p.theme)}','${esc(p.category)}','${esc(p.status)}','${esc(p.hash)}',${p.version | 0},'${esc(p.share_key)}','${esc(payload)}');`
  );
}
for (const [day, id] of Object.entries(schedule)) {
  lines.push(`INSERT INTO ws_schedule (day, puzzle_id) VALUES ('${esc(day)}','${esc(id)}');`);
}
const out = path.join("data", "ws-production.sql");
fs.writeFileSync(out, lines.join("\n") + "\n");
console.log(`${out}: ${puzzles.length} boards, ${Object.keys(schedule).length} schedule days, XI invariant held on all ${puzzles.length}.`);
