/* import_grid_test.mjs — the calendar cannot be rewritten by accident.
 *
 * WHAT THIS IS ABOUT. Grid XI's calendar is rebuilt from the launch day on
 * every import: board 1 is day 1, board 2 is day 2, and so on down the source
 * order. Marking a board `free` — which is the whole point of the catalogue,
 * and the thing the owner is about to start doing — takes it OUT of that run
 * and closes the days up behind it.
 *
 * For the days still to come, that is exactly what is wanted. For the days
 * already played it is a rewrite of history: a result banked on Monday, that
 * Monday's archive entry and that Monday's answers page would all then be
 * about a board that was never Monday's daily. The word search has already
 * had to close its version of this — an answers page publishing boards that
 * had never run — and it was 233 boards deep before anybody noticed.
 *
 * So the importer compares what it is about to write with what it wrote last
 * time and refuses to move a day that is in the past. The comparison is two
 * pure functions, and this runs them.
 *
 *   node tools/import_grid_test.mjs        (from the repo root)
 */
import { scheduleFromSql, historyClash, carryForward, buildSchedule, uncoveredPast } from "./import_grid.js";

let pass = 0, fail = 0;
const t = (n, ok, d) => { ok ? pass++ : fail++; console.log(`${ok ? "  ok  " : "FAIL  "}${n}${d ? "  — " + d : ""}`); };

const SQL = `-- Grid XI: the boards and the calendar. GENERATED by tools/import_grid.js.
-- 3 boards, 3 days, from 2026-09-07 to 2026-09-09.

DELETE FROM gd_schedule;

INSERT OR REPLACE INTO gd_board (id, set_id, kind, title, rows, cols, payload, updated_at) VALUES ('gx-0001', 'a', 'daily', 'One', 3, 3, '{}', 'now');
INSERT OR REPLACE INTO gd_board (id, set_id, kind, title, rows, cols, payload, updated_at) VALUES ('gx-0002', 'b', 'daily', 'Two', 3, 3, '{}', 'now');

INSERT INTO gd_schedule (day, board_id) VALUES ('2026-09-07', 'gx-0001');
INSERT INTO gd_schedule (day, board_id) VALUES ('2026-09-08', 'gx-0002');
INSERT INTO gd_schedule (day, board_id) VALUES ('2026-09-09', 'gx-0003');
`;

console.log("The calendar that was written last time is readable");
{
  const got = scheduleFromSql(SQL);
  t("every day comes back with the board it named",
    Object.keys(got).length === 3 && got["2026-09-07"] === "gx-0001" &&
    got["2026-09-08"] === "gx-0002" && got["2026-09-09"] === "gx-0003",
    JSON.stringify(got));
  /* The file holds INSERTs into two tables and only one of them is a calendar.
     A reader that took board ids out of the gd_board lines would compare a
     calendar against a bank. */
  t("and the board rows are not mistaken for calendar rows",
    !Object.values(got).includes("a") && !Object.keys(got).includes("gx-0001"));
  t("a file that is not there at all is an empty calendar, not a crash",
    Object.keys(scheduleFromSql("")).length === 0 &&
    Object.keys(scheduleFromSql(null)).length === 0);
}

console.log("\nA day that has been played cannot be moved");
{
  const prev = scheduleFromSql(SQL);
  const TODAY = "2026-09-09";

  /* THE ACTUAL SCENARIO: gx-0001 is marked free, so it leaves the calendar and
     everything behind it moves up a day. The two days already played now name
     boards they never ran. */
  const shifted = { "2026-09-07": "gx-0002", "2026-09-08": "gx-0003", "2026-09-09": "gx-0004" };
  const clash = historyClash(prev, shifted, TODAY);
  t("taking one board out shifts every played day, and every one is named",
    clash.length === 2 && clash[0].day === "2026-09-07" &&
    clash[0].was === "gx-0001" && clash[0].now === "gx-0002",
    clash.map((c) => `${c.day}: ${c.was}->${c.now}`).join(", "));
  /* TODAY IS NOT THE PAST. A re-import that changes today and everything after
     it is a re-import doing its job. */
  t("and today is left out of it, because today is still to come",
    !clash.some((c) => c.day >= TODAY), "the future is what a re-import is for");

  const gone = { "2026-09-07": "gx-0001", "2026-09-09": "gx-0004" };
  const missing = historyClash(prev, gone, TODAY);
  t("a played day that vanishes from the calendar counts too",
    missing.length === 1 && missing[0].day === "2026-09-08" && missing[0].now === null,
    "a played day with no board at all is the same lie by omission");

  t("an unchanged past is no clash at all, so an ordinary re-import still runs",
    historyClash(prev, scheduleFromSql(SQL), TODAY).length === 0,
    "the guard must not stand in the way of the import it was written for");
  t("and a calendar that has not started yet has nothing to protect",
    historyClash(prev, shifted, "2026-09-01").length === 0);
}

console.log("\nA re-import keeps the past and does not serve a board twice");
{
  /* THE OPERATION ALL OF THIS IS FOR. Marking boards for the catalogue takes
     them out of the daily run and the calendar is rebuilt; the two things that
     must not happen are a played day changing and a board being handed to
     somebody twice.

     Days are the importer's own, counted from the launch epoch, so this asks
     for the SHAPE — what was kept, and which boards fill what follows. */
  const boards = [
    { id: "gx-0001", kind: "daily" },
    { id: "gx-0002", kind: "free" },      // was a daily, now the catalogue's
    { id: "gx-0003", kind: "daily" },
    { id: "gx-0004", kind: "daily" },
    { id: "gx-0005", kind: "transient" }, // a matchweek board: never a day
  ];
  const prev = { "2026-09-07": "gx-0001", "2026-09-08": "gx-0002" };
  const FROM = "2026-09-09";

  const kept = carryForward(prev, FROM);
  t("every day before the start day is carried forward, exactly as it was",
    Object.keys(kept).length === 2 && kept["2026-09-07"] === "gx-0001" &&
    kept["2026-09-08"] === "gx-0002",
    "gx-0002 still ran on the 8th, even though it is a catalogue board now");
  t("and nothing from the start day on is carried",
    carryForward({ ...prev, "2026-09-09": "gx-0003" }, FROM)["2026-09-09"] === undefined,
    "from there it is rebuilt, which is the point of the re-import");

  const sched = buildSchedule(boards, FROM, kept);
  const days = Object.keys(sched).sort();
  t("the past survives the rebuild",
    sched["2026-09-07"] === "gx-0001" && sched["2026-09-08"] === "gx-0002",
    days.slice(0, 2).join(", "));
  const future = days.filter((d) => d >= FROM).map((d) => sched[d]);
  t("and no board the past already served is served again",
    !future.includes("gx-0001") && !future.includes("gx-0002"),
    future.join(", ") + " — gx-0001 and gx-0002 have been played");
  t("a catalogue board takes no day at all", !future.includes("gx-0002"));
  t("nor does a transient one", !future.includes("gx-0005"),
    "the matchweek boards are a rolling window, not a calendar day");
  t("the remaining dailies fill the days in order",
    future.join(",") === "gx-0003,gx-0004", future.join(", "));

  /* AND THE WHOLE THING PASSES ITS OWN GUARD, which is the property that
     matters: this is the shape of re-import that does not rewrite history. */
  t("so the history guard finds nothing to refuse",
    historyClash(prev, sched, FROM).length === 0,
    "the operation the guard was written to allow");
}

/* ---- the hole under the history check ----------------------------------
 *
 * THIS GAME IS THE REASON IT MATTERS. Grid's live calendar is a placeholder
 * dated from the day it was imported, and CLAUDE.md records that it must be
 * re-imported with --from=<launch day> when the game launches. That is exactly
 * a run with a start day in the past.
 *
 * Grid is not currently exposed — its calendar starts 2026-09-06 and does record
 * days that have run, so historyClash has something to compare — but the guard
 * should not depend on that being true. Against a calendar holding no past day
 * historyClash examines nothing, returns zero, and the run writes over served
 * days while reporting a clean bill.
 *
 * Found in import_ballpark.js by the Connection session, reproduced there, and
 * the same shape confirmed here. Grid's was worse in one respect: its whole
 * clash block sat behind `if (fs.existsSync(OUT))`, so deleting the staged SQL
 * removed the guard rather than tripping it.
 */
console.log("\nThe past must be accounted for, not merely unmentioned");
{
  const today = "2026-09-15";

  const futureOnly = { "2026-09-22": "gd-1", "2026-09-23": "gd-2" };
  t("a calendar that records no past day leaves every past day uncovered",
    uncoveredPast(futureOnly, "2026-09-09", today).length === 6,
    uncoveredPast(futureOnly, "2026-09-09", today).join(", "));
  t("and historyClash finds nothing there, which is why it is not enough",
    historyClash(futureOnly, {}, today).length === 0,
    "zero clashes against a calendar with no past day");

  const covered = {};
  for (let d = 9; d <= 15; d++) covered[`2026-09-${String(d).padStart(2, "0")}`] = "gd-" + d;
  t("a calendar covering every past day is permitted",
    uncoveredPast(covered, "2026-09-09", today).length === 0,
    "the launch-day re-import this game still owes is not blocked");

  const partial = { "2026-09-09": "gd-9", "2026-09-10": "gd-10" };
  t("a partial calendar names exactly the days it cannot speak for",
    uncoveredPast(partial, "2026-09-09", today).join(",") ===
      "2026-09-11,2026-09-12,2026-09-13,2026-09-14",
    uncoveredPast(partial, "2026-09-09", today).join(", "));

  t("a start day today or later is not this check's business",
    uncoveredPast({}, today, today).length === 0 &&
    uncoveredPast({}, "2026-09-20", today).length === 0);

  t("and a missing calendar with a past start is still refused",
    uncoveredPast({}, "2026-09-09", today).length === 6,
    "deleting the staged SQL must not delete the guard");
}

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
