/* import_grid_test.mjs — the calendar cannot be rewritten by accident.
 *
 * WHAT THIS IS ABOUT. Grid XI's calendar is rebuilt from the launch day on
 * every import: board 1 is day 1, board 2 is day 2, and so on down the source
 * order. Marking a board `free` — which is the whole point of the catalogue,
 * and the thing the owner is about to start doing — takes it OUT of that run
 * and closes the days up behind it.
 *
 * For the days still to come, that is exactly what is wanted. For the days
 * already played it is a rewrite of history: a result banked on Monday, that
 * Monday's archive entry and that Monday's answers page would all then be
 * about a board that was never Monday's daily. The word search has already
 * had to close its version of this — an answers page publishing boards that
 * had never run — and it was 233 boards deep before anybody noticed.
 *
 * So the importer compares what it is about to write with what it wrote last
 * time and refuses to move a day that is in the past. The comparison is two
 * pure functions, and this runs them.
 *
 *   node tools/import_grid_test.mjs        (from the repo root)
 */
import { scheduleFromSql, historyClash } from "./import_grid.js";

let pass = 0, fail = 0;
const t = (n, ok, d) => { ok ? pass++ : fail++; console.log(`${ok ? "  ok  " : "FAIL  "}${n}${d ? "  — " + d : ""}`); };

const SQL = `-- Grid XI: the boards and the calendar. GENERATED by tools/import_grid.js.
-- 3 boards, 3 days, from 2026-09-07 to 2026-09-09.

DELETE FROM gd_schedule;

INSERT OR REPLACE INTO gd_board (id, set_id, kind, title, rows, cols, payload, updated_at) VALUES ('gx-0001', 'a', 'daily', 'One', 3, 3, '{}', 'now');
INSERT OR REPLACE INTO gd_board (id, set_id, kind, title, rows, cols, payload, updated_at) VALUES ('gx-0002', 'b', 'daily', 'Two', 3, 3, '{}', 'now');

INSERT INTO gd_schedule (day, board_id) VALUES ('2026-09-07', 'gx-0001');
INSERT INTO gd_schedule (day, board_id) VALUES ('2026-09-08', 'gx-0002');
INSERT INTO gd_schedule (day, board_id) VALUES ('2026-09-09', 'gx-0003');
`;

console.log("The calendar that was written last time is readable");
{
  const got = scheduleFromSql(SQL);
  t("every day comes back with the board it named",
    Object.keys(got).length === 3 && got["2026-09-07"] === "gx-0001" &&
    got["2026-09-08"] === "gx-0002" && got["2026-09-09"] === "gx-0003",
    JSON.stringify(got));
  /* The file holds INSERTs into two tables and only one of them is a calendar.
     A reader that took board ids out of the gd_board lines would compare a
     calendar against a bank. */
  t("and the board rows are not mistaken for calendar rows",
    !Object.values(got).includes("a") && !Object.keys(got).includes("gx-0001"));
  t("a file that is not there at all is an empty calendar, not a crash",
    Object.keys(scheduleFromSql("")).length === 0 &&
    Object.keys(scheduleFromSql(null)).length === 0);
}

console.log("\nA day that has been played cannot be moved");
{
  const prev = scheduleFromSql(SQL);
  const TODAY = "2026-09-09";

  /* THE ACTUAL SCENARIO: gx-0001 is marked free, so it leaves the calendar and
     everything behind it moves up a day. The two days already played now name
     boards they never ran. */
  const shifted = { "2026-09-07": "gx-0002", "2026-09-08": "gx-0003", "2026-09-09": "gx-0004" };
  const clash = historyClash(prev, shifted, TODAY);
  t("taking one board out shifts every played day, and every one is named",
    clash.length === 2 && clash[0].day === "2026-09-07" &&
    clash[0].was === "gx-0001" && clash[0].now === "gx-0002",
    clash.map((c) => `${c.day}: ${c.was}->${c.now}`).join(", "));
  /* TODAY IS NOT THE PAST. A re-import that changes today and everything after
     it is a re-import doing its job. */
  t("and today is left out of it, because today is still to come",
    !clash.some((c) => c.day >= TODAY), "the future is what a re-import is for");

  const gone = { "2026-09-07": "gx-0001", "2026-09-09": "gx-0004" };
  const missing = historyClash(prev, gone, TODAY);
  t("a played day that vanishes from the calendar counts too",
    missing.length === 1 && missing[0].day === "2026-09-08" && missing[0].now === null,
    "a played day with no board at all is the same lie by omission");

  t("an unchanged past is no clash at all, so an ordinary re-import still runs",
    historyClash(prev, scheduleFromSql(SQL), TODAY).length === 0,
    "the guard must not stand in the way of the import it was written for");
  t("and a calendar that has not started yet has nothing to protect",
    historyClash(prev, shifted, "2026-09-01").length === 0);
}

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
