/* friends/crossword/daily_test.mjs — what /api/crossword_fr/daily will and
 * will not send.
 *
 * IT RUNS THE REAL ROUTE against a stubbed D1. The stub re-applies the lookup
 * in JS, which is right — a stub that rubber-stamped would prove nothing — but
 * it means a bound dropped from the real SQL would pass here. That is this
 * project's own rule arriving in person: a stubbed database cannot prove a
 * query. What IS proved here is that the route passes the right binds, reads
 * the result correctly, and refuses what it must. The QUERY is proved in the
 * live_check, against real D1.
 *
 * THE BOARD IS GENERATED BY THE REAL ENGINE, never written out here. This file
 * hand-built one at first, with `entry.cells` as an array of "x,y" STRINGS —
 * and the engine emits { x, y } OBJECTS. Production code indexing the cell map
 * with the object got undefined every time, QUIETLY, so the marker read every
 * answer as blank and the leak scan searched for nothing and passed. Every case
 * below passed too, because the fixture had been written by the same hand as
 * the bug. See fixture.mjs.
 *
 * LAUNCHED IS USED AS A FIXTURE, deliberately. crossword_fr is not launched, so
 * every launched-path case below would otherwise be unreachable — and "not out
 * yet" and the archive rule are exactly the behaviour that has to be right ON
 * the day it launches, not discovered then. The key is set and deleted around
 * each case, and the last case asserts it is absent again, because a suite that
 * left it set would quietly launch the game for every other suite in the run.
 */

import { onRequestGet, onRequestHead } from "../../functions/api/crossword_fr/daily.js";
import { LAUNCHED, launchNumber } from "../../functions/_lib/games.js";
import { dailyDayKey, dailyNumber } from "../../functions/_lib/daily.js";
import { makeBoard, answersOf, title } from "./fixture.mjs";

let pass = 0, fail = 0;
const t = (n, ok, d) => {
  ok ? pass++ : fail++;
  console.log(`${ok ? "  ok  " : "FAIL  "}${n}${d ? "  — " + d : ""}`);
};

const norm = (s) => String(s).toUpperCase().replace(/[^A-Z0-9]/g, "");
const answers = (p) => answersOf(p).map((a) => a.letters);

/* ---- the stub ----------------------------------------------------------- */

function db(rows, seen) {
  return {
    DB: {
      prepare: (sql) => ({
        bind: (...args) => ({
          first: async () => {
            if (seen) { seen.sql = sql; seen.args = args; }
            if (!/FROM fr_puzzles/.test(sql)) return null;
            if (!/mode = 'daily'/.test(sql)) return null;
            const no = Number(args[0]);
            const r = rows.find((x) => x.no === no);
            return r ? { payload: r.payload } : null;
          },
        }),
      }),
    },
  };
}

const req = (qs) =>
  new Request("https://thexigames.com/api/crossword_fr/daily" + (qs || ""));
const get = async (rows, qs, seen) =>
  onRequestGet({ request: req(qs), env: db(rows, seen) });
const body = async (r) => { try { return await r.clone().json(); } catch { return null; } };

const rowsFor = (puzzle, nos) =>
  (nos || [1]).map((no) => ({ no, payload: JSON.stringify({ puzzle }) }));

const BOARD = makeBoard();
const ONE = rowsFor(BOARD);

/* ---- before launch ------------------------------------------------------ */

console.log("=== Before launch there is no today ===");
{
  t("crossword_fr really is unlaunched", !LAUNCHED.crossword_fr,
    "every case in this file depends on it");

  const r = await get(ONE);
  const b = await body(r);
  t("a bare request answers 200 rather than erroring", r.status === 200, String(r.status));
  t("and says so plainly", b && b.board === null && b.launched === false,
    JSON.stringify(b && { board: b.board, launched: b.launched }));
  t("and does not invent board 1", b && b.no === null && b.today === null,
    JSON.stringify(b && { no: b.no, today: b.today }));

  const e = await get(ONE, "?no=1");
  const eb = await body(e);
  t("an explicit ?no= still serves, so the game is buildable",
    e.status === 200 && eb && eb.board && eb.board.entries.length === 11,
    `${e.status}, ${eb && eb.board ? eb.board.entries.length : 0} entries`);
}

/* ---- what is a board number --------------------------------------------- */

console.log("\n=== A board number is a board number ===");
for (const q of ["?no=0", "?no=-1", "?no=abc", "?no=1.5", "?no="]) {
  const r = await get(ONE, q);
  t(`${q} is refused`, r.status === 400, String(r.status));
}

/* ---- the answers may not leave ------------------------------------------ */

console.log("\n=== The answers may not leave ===");
{
  const r = await get(ONE, "?no=1");
  const b = await body(r);

  t("no cell carries a letter",
    Object.values(b.board.cells).every((c) => !("ch" in c)),
    Object.keys(b.board.cells).length + " cells");

  const all = answers(BOARD);
  t("PRECONDITION: there are answers to look for",
    all.length === 11 && all.every((a) => a.length > 2),
    `${all.length} answers, shortest ${Math.min(...all.map((a) => a.length))}`);

  /* VALUES, WALKED — NEVER THE SERIALISED RESPONSE. Normalising JSON.stringify
     turns KEY NAMES into searchable letters, and this suite proved it twice on
     itself: ROSS is inside the entry's `dir: "across"`, and after that was
     excluded it was still inside the key name `across` of every cell object.
     ROSS is a real Friends answer — 131 bank rows — so a scan built that way
     reports a leak on any board that contains it. That is not hypothetical: the
     route's first scan did exactly this and would have refused 24 of the 120
     boards now in D1, board 1 among them.
     Walking values gets both right for free: a key is never read, and each
     value is tested whole rather than glued to its neighbours. Written here
     independently of how the route does it, so the two can disagree. */
  const values = (v, out) => {
    if (v == null) return out;
    if (typeof v === "string") { out.push(v); return out; }
    if (typeof v !== "object") return out;
    for (const k of Object.keys(v)) values(v[k], out);
    return out;
  };
  const served = values(b.board, []);
  const clues = new Set(b.board.entries.map((e) => e.row.clue));

  t("PRECONDITION: the response really does carry values to search",
    served.length > 20, `${served.length} string values`);
  t("not one of the eleven answers is inside any served value", (() => {
    /* The clue is excluded for the reason the importer excludes it: three bank
       rows legitimately contain their own answer inside a longer word. */
    const hay = served.filter((s) => !clues.has(s)).map(norm);
    return all.every((a) => !hay.some((h) => h.includes(a)));
  })(), `${all.length} answers against ${served.length - clues.size} values`);

  t("no entry carries answer, grid or sourceQuote",
    b.board.entries.every((e) =>
      !("answer" in e.row) && !("grid" in e.row) && !("sourceQuote" in e.row)));
  t("but the clue does go out, because it must",
    b.board.entries.every((e) => typeof e.row.clue === "string" && e.row.clue.length));
}

/* ---- the last-chance scan ----------------------------------------------- */

console.log("\n=== The scan between the database and the player ===");
{
  /* The importer gates every board before it is written. This proves the route
     does NOT rely on that — between the two the board goes through a database
     and a JSON round trip, and a leak that only appears in production is the
     one shape nothing offline can see. */
  const inCat = makeBoard((w, i) => (i === 0 ? { cat: `Fixture > ${title(w)}` } : {}));
  const r = await get(rowsFor(inCat), "?no=1");
  t("a board whose category carries its own answer is refused", r.status === 500,
    String(r.status));
  const refusal = JSON.stringify((await body(r)) || {});
  t("and the refusal names no answer",
    !answers(inCat).some((a) => norm(refusal).includes(a)), refusal);

  const inEra = makeBoard((w, i) => (i === 3 ? { era: title(w) } : {}));
  t("the same in another served field",
    (await get(rowsFor(inEra), "?no=1")).status === 500);

}
{
  /* THE REGRESSION. The scan first read the whole public board INCLUDING the
     clues, which would have refused the three bank rows whose answer sits
     inside a longer word in their own clue — MONKEY in "two monkeys", MONICA
     in "Harmonica", HANDLER in "Chandler". */
  const legit = makeBoard((w, i) =>
    (i === 0 ? { clue: `Who plays the Har${w.toLowerCase()} at the party?` } : {}));
  t("a clue that legitimately contains its own answer still serves",
    (await get(rowsFor(legit), "?no=1")).status === 200);
}
{
  /* AND THE OTHER HALF OF THAT COLLISION, which cost 24 boards. An answer that
     is a substring of the board's own STRUCTURE must not be mistaken for a
     leak. ROSS is in the fixture bank precisely so this case exists. */
  const all = answers(BOARD);
  t("PRECONDITION: an answer really is inside the structure word 'across'",
    all.some((a) => norm("across").includes(a)),
    all.filter((a) => norm("across").includes(a)).join(",") || "none — case is vacuous");
  t("and the board carrying it serves anyway",
    (await get(ONE, "?no=1")).status === 200);
}

/* ---- a board that is not there ------------------------------------------ */

console.log("\n=== A board that is not there ===");
{
  const r = await get(ONE, "?no=99");
  const b = await body(r);
  t("is not an error", r.status === 200, String(r.status));
  t("and says board: null", b && b.board === null);

  t("an unreadable payload is a 500",
    (await get([{ no: 1, payload: "{not json" }], "?no=1")).status === 500);
  t("and so is a payload that is not a puzzle",
    (await get([{ no: 1, payload: JSON.stringify({ puzzle: { nope: true } }) }], "?no=1"))
      .status === 500);
}

/* ---- the binds ---------------------------------------------------------- */

console.log("\n=== The binds the route actually passes ===");
{
  const seen = {};
  await get(ONE, "?no=1", seen);
  t("it asks fr_puzzles", /FROM fr_puzzles/.test(seen.sql || ""), seen.sql);
  t("for the daily mode", /mode = 'daily'/.test(seen.sql || ""));
  t("bound to the board number, not interpolated",
    seen.args && seen.args.length === 1 && Number(seen.args[0]) === 1,
    JSON.stringify(seen.args));
}

/* ---- HEAD --------------------------------------------------------------- */

console.log("\n=== HEAD ===");
{
  const r = await onRequestHead({ request: req("?no=1"), env: db(ONE) });
  t("answers 200", r.status === 200, String(r.status));
  t("with an empty body", (await r.text()) === "");
  t("and no-store, so no shared cache holds a board",
    /no-store/.test(r.headers.get("Cache-Control") || ""),
    r.headers.get("Cache-Control"));
}

/* ---- once it launches --------------------------------------------------- */

console.log("\n=== Once it launches ===");
{
  /* THE PUBLIC NUMBER IS THE FAMILY'S, and this block exists because this file
     asserted the opposite and was wrong. It pinned "today is board 2, counted
     from ITS launch and not the family epoch" — which is exactly the bug:
     boardKeys() advertises launchNumber(game)..today, so the sitemap would have
     linked /friends/crossword/daily/N while the route read N as the bank's Nth
     board and served the wrong puzzle. Vowels launched on board TEN for this
     reason; a game's first board is not board 1 here.
     fr-board.js owns the conversion, and these cases hold the route to it. */
  const famToday = dailyNumber(Date.now());
  const launchDay = dailyDayKey(famToday - 1);            // launched yesterday
  LAUNCHED.crossword_fr = launchDay;
  try {
    const from = launchNumber("crossword_fr");
    t("PRECONDITION: the launch is NOT the family epoch", from > 1,
      `launchNumber ${from} — at 1 the two numberings coincide and every ` +
      `assertion below would hold under either rule, which is how the old ` +
      `version of this block passed while the route was wrong`);

    /* Stored rows are the bank's 1..120, which is NOT what the URL carries. */
    const rows = [1, 2, 3].map((no) => ({ no, payload: JSON.stringify({ puzzle: BOARD }) }));

    const r = await get(rows);
    const b = await body(r);
    t("a bare request serves today's board", r.status === 200 && b.board !== null,
      String(r.status));
    t("and today's number is the FAMILY's, not one counted from the launch",
      b.today === famToday && b.no === famToday,
      JSON.stringify({ no: b.no, today: b.today, family: famToday }));
    t("which is the day it says it is", b.day === dailyDayKey(famToday), b.day);

    /* THE CASE THE BUG WOULD HAVE BROKEN: the launch day's public number must
       reach the bank's FIRST board, not its `from`-th. The stub answers only
       stored rows 1..3, so asking for the launch day and getting a board at all
       proves the offset was applied. */
    const opening = await get(rows, "?no=" + from);
    t("the launch day's public number reaches the bank's first board",
      opening.status === 200 && (await opening.clone().json()).board !== null,
      `?no=${from} -> ${opening.status}`);

    /* And the mirror: the number the OLD code would have used for the opening
       board must NOT be today's board. With the launch one day back, board 1 of
       the bank is yesterday, so a naive 1 addresses a day before the game
       existed and there is nothing there. */
    const naive = await get(rows, "?no=1");
    const nb = await body(naive);
    t("and a bare 1 is a day before the game existed, so no board",
      naive.status === 200 && nb.board === null,
      `?no=1 -> ${naive.status}, board ${nb && nb.board === null ? "null" : "SERVED"}`);

    t("tomorrow is refused", (await get(rows, "?no=" + (famToday + 1))).status === 403);
    t("and so is a number far in the future",
      (await get(rows, "?no=" + (famToday + 400))).status === 403);

    /* RUNWAY. The bank holds 120 boards; the day after the last of them is a
       day the calendar has reached and the bank has not. It answers with no
       board rather than wrapping round to board 1, which would hand a player a
       puzzle they have already had. */
    t("the route reports where the bank runs out", typeof nb.lastBoardNo === "number",
      "lastBoardNo " + nb.lastBoardNo);
    t("and that is the launch number plus the bank, less one",
      nb.lastBoardNo === from + 120 - 1, String(nb.lastBoardNo));
  } finally {
    delete LAUNCHED.crossword_fr;
  }
  t("and the fixture is removed again", !LAUNCHED.crossword_fr,
    "a suite that left this set would launch the game for every suite after it");
}

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
